### ISSUE TITLE
Backup your wallet to password manager

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#102]
Many users use 1Password, Last pass for storing all the private information. I would like to have the generic integration that will support all of them.

to build simple functionality we want to have an ability to backup your keystore with a password at first. Import functionality could be done manually by the users.

It would be stored in this format:

Service/Name: Trust
Account: 0x.... - hex address
Password: Password to the keystore
Notes(Secure notes): keystore in JSON format

Reference: https://github.com/joelastpass/generic-password-app-extension

**Comment by anna64000** [comment]
thanks

**Comment by michaelScoff** [comment]
Will come back later
