### ISSUE TITLE
Fees

### ISSUE THREAD

**Issue by BifocalComb** [TrustWallet/trust-wallet-ios#115]
Please allow a custom fee option as my erc20 tokens are stuck indefinitely due to high network traffic

**Comment by michaelScoff** [comment]
https://twitter.com/trustwalletapp/status/938604771539238913

We got you covered!

**Comment by BifocalComb** [comment]
Oops, I'll have to follow you on Twitter too. Thanks!

**Comment by michaelScoff** [comment]
Also in the build i check gas price with the network, if will tell me average price for transaction, that will be used as default
