### ISSUE TITLE
Add Backup Private Key from wallets list

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#123]
- Implement export private key functionality
- Add ability to export private key from info button in wallets list

**Comment by yaleidev** [comment]
hi, are you solved?  @michaelScoff 
export private key?

**Comment by michaelScoff** [comment]
@yaleidev yo! It’s not resolve it. Feel free to send pull request for it!

**Comment by vikmeup** [comment]
https://github.com/TrustWallet/trust-wallet-ios/blob/master/Trust/EtherClient/EtherKeystore.swift

This is how we convert private key into keystore, if you do reverse operation you could get private key back

**Comment by michaelScoff** [comment]
https://github.com/TrustWallet/trust-wallet-ios/blob/5609eadfd6db7708a15057f9b63ea8394594ffe4/Trust/EtherClient/EtherKeystore.swift#L267

This is how we convert private key into keystore, if you do reverse operation you could get private key back from the keystore

**Comment by yaleidev** [comment]
func convertKeystoreFileToPrivateKey(value: String, passphrase: String) -> Result<String, KeystoreError> {
        
        guard let json = JSON.init(parseJSON: value).dictionaryObject else {
            return .failure(KeystoreError.failedToImportPrivateKey)
        }
        
        do {
            let passphraseBytes: [UInt8] = Array(passphrase.utf8)
            // reduce this number for higher speed. This is the default value, though. n
            
            let crypto = json["crypto"] as! [String: Any]
            
            let kdfparams = crypto["kdfparams"] as! [String: Any]
            let cipherparams = crypto["cipherparams"] as! [String: Any]
            let sa = kdfparams["salt"] as! String
            let numberOfIterations = kdfparams["n"] as! Int
            let ia = cipherparams["iv"] as! String
            let cip = crypto["ciphertext"] as! String
            
            Log(sa)
            Log(numberOfIterations)
            Log(ia)
            Log(cip)
            
            let salt: [UInt8] = Array(sa.utf8)
            
            let derivedKey = try PKCS5.PBKDF2(password: passphraseBytes, salt: salt, iterations: numberOfIterations, variant: .sha256).calculate()
            
            Log(derivedKey)
            
            let iv: [UInt8] = Array(ia.utf8)
            let aes = try AES(key: Array(derivedKey), blockMode: .CTR(iv: iv), padding: .noPadding)
            

            let ciphertext: [UInt8] = Array(cip.utf8)
            
            let key = try aes.decrypt(ciphertext)
            
            let privateKey = key.toHexString()
            Log(privateKey)
            
            return .success(privateKey)
        } catch {
            return .failure(KeystoreError.failedToImportPrivateKey)
        }
    }

i'm try to convertKeystoreFileToPrivateKey fuc.
but it is not successful. it failure.
can u help me. .
@michaelScoff

**Comment by michaelScoff** [comment]
can you contact me on telegram: vikmeup? let's figure this out together

**Comment by yaleidev** [comment]
hi,What is your skype?
my skype is yaleime@gmail.com

**Comment by yaleidev** [comment]
@michaelScoff thks.

**Comment by yaleidev** [comment]
i have skype yaleime@gmail.com
i am stay in china.no telegram..
@michaelScoff 
do you have skype?

**Comment by michaelScoff** [comment]
I think it would be best to show where you have backup Keystore, that says Export Private Key. 

On the page there would be warning sign that says private key should be kept secure. 

And you have huge QR code that’s blurred and you need to press reveal in order to see it! 

I just want to make sure user understand what is he doing.

**Comment by MillerApps** [comment]
I have exporting working, just need to get the UI done now.

**Comment by vikmeup** [comment]
@michaelScoff feel free to push changes before doing UI part

**Comment by MillerApps** [comment]
@vikmeup okay, I’ll do so when I get home. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
Implemented
