### ISSUE TITLE
Implement EIP55

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#130]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md

**Comment by OlegGordiichuk** [comment]
@aleph7 If you could share the implementation of this step it will be grate.

**Comment by aleph7** [comment]
Almost done

**Comment by aleph7** [comment]
Use trust-keystore 0.0.5

**Comment by aleph7** [comment]
Just missing the user-facing piece

**Comment by anna64000** [comment]
ok
