### ISSUE TITLE
Where is my ether?

### ISSUE THREAD

**Issue by waveheat** [TrustWallet/trust-wallet-ios#135]
I added some additional addresses to my wallet and bought some ether from a bitcoin ATM over 24 hours ago but it’s still not showing in my balance, even though the ether I bought after those ones (to my default wallet address) have shown up. I’m freaking out now. I hope I haven’t lost my money.

**Comment by michaelScoff** [comment]
Do you have transaction ID for your transfer?  What wallet address did you use? I can take a look

**Comment by waveheat** [comment]
Hi,
I bought it from an ATM yesterday, and sent it to my ‘Trust Wallet’

**Comment by waveheat** [comment]
...I don’t have a transaction ID

**Comment by michaelScoff** [comment]
How do you know they sent it to your wallet? 

I have a user, he used ATM as well, it’s been over 24 hours but his status still pending.

**Comment by michaelScoff** [comment]
Please reach out to ATM contact support and ask for more information. 

Trust wallet just pulls data from ethereum network

**Comment by waveheat** [comment]
The ATM (statoshipoint) had a screen that said ‘transaction successful’

**Comment by michaelScoff** [comment]
Do you have any receipts? Or any information about your transfer 

If you had that, you can check on the blockchain if they sent it to you

**Comment by waveheat** [comment]
Hi,
Thank you for all your help.
I contacted the ATM provider and was able to get my money returned to me, despite not having a receipt (it took a good few hours for them to investigate the case)

**Comment by michaelScoff** [comment]
@waveheat do you know what was the issue with ATM? just curious.

I will close this issue since it's resolved.
