### ISSUE TITLE
Currency support

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#144]
Coinmarkercap has support for many currencies at the moment, we could use that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OlegGordiichuk** [comment]
I will take this issue. For start I will add support of custom tokens icons and current rate in USD. Is it ok @michaelScoff for you? Or you have another ideas ? All data will be taken from Coinmarkercap including images.

**Comment by michaelScoff** [comment]
We have current prices for tokens implemented already, but custom currency setting would be awesome! 

Also I have some ideas regarding creating open database of token images.  

Could your telwgram: vikmeup? I can explain. Thanks 

And thank you so much for helping

**Comment by OlegGordiichuk** [comment]
@michaelScoff done.

We could take them from https://files.coinmarketcap.com/static/img/coins/32x32/nem.png 

So there is no need to creating open database.

**Comment by anna64000** [comment]
Thanks
