### ISSUE TITLE
Status bar squished on iPad

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#162]
![GitHawk Upload by michaelScoff](https://i.imgur.com/cDEkr5M.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by michaelScoff** [comment]
@OlegGordiichuk do you know why this could happen? seemed like related to hiding navigation bar? 
I believe it's iOS 10 iPad

**Comment by OlegGordiichuk** [comment]
I will take a look
