### ISSUE TITLE
Export private key

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#169]
Add ability to export private key

**Comment by aleph7** [comment]
This is already supported by trust-keystore. We just need the UI for it.

**Comment by michaelScoff** [comment]
@aleph7 I will have this hooked up!

**Comment by michaelScoff** [comment]
@OlegGordiichuk wanna take a look at this one? I think we should make it look pretty much the same as `My Address`, but we should have a red label saying DO NOT SHARE THIS?

**Comment by michaelScoff** [comment]
@aleph7 I only see `KeyStore` exposing export keystore, could you add the export private key as well?
