### ISSUE TITLE
Add share transaction id feature (and replacing "More Detail" in the meanwhile?)

### ISSUE THREAD

**Issue by colourful-land** [TrustWallet/trust-wallet-ios#171]
When a user clicks a transaction, he will see a transaction detail page, which includes all information a transaction should have. At this point, the user's most likely action is not to see even more details like nonce - that "More Details" button serve to surprise the user by opening the browser. 

The likely course of action at this point is to copy the Transaction ID, probably to send to his friend to say that the money was successfully sent (or received).

**Comment by michaelScoff** [comment]
@colourful-land Hey! Thank you for the feedback.
Since we don't provide full information about the transaction, there is alternative service such as Etherscan to see details.

You can also press transaction ID to copy it.

How about adding a button in the top right button to share this transaction ID instead? Similar how it's done in my address view?

**Comment by colourful-land** [comment]
That's a fast reply and a good idea!

**Comment by michaelScoff** [comment]
What if I told that it's has been implemented? https://github.com/TrustWallet/trust-wallet-ios/commit/e30e18aadf3fa1f3e6adf871f80622cb53e975a0

Check out attached gif.

![test](https://user-images.githubusercontent.com/32179653/34338822-3730ddd0-e921-11e7-8fac-c060c0bc781d.gif)

**Comment by colourful-land** [comment]
That is super fast!! Fastest ever in my 8 years using github/sourceforge!

**Comment by michaelScoff** [comment]
@colourful-land :) Sorry I could have done this faster though. I just got a new mac book pro, I had to install https://github.com/klaaspieter/xcrecord to record gifs from the Xcode. 

App Store on vacation until 27 of Dec 😢, I will push build out in few days for everyone.
