### ISSUE TITLE
Ability to Enter value in USD/ETH or tokens

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#180]
<img width="669" alt="screen shot 2018-01-02 at 3 24 53 pm" src="https://user-images.githubusercontent.com/32179653/34504125-45008fda-efd1-11e7-8f6c-c048bc1ca5a9.png">

We need to have the ability to enter the value in USD(or currently selected currency), ETH or in tokens

when you press on ETH it would show picker to select USD(), ETH(or current symbol), and list of enabled tokens

**Comment by mercuriosilber** [comment]
It would be even better if you could choose any currency equivalent when sending tokens.

**Comment by michaelScoff** [comment]
@mercuriosilber same coming to tokens :) Thanks
