### ISSUE TITLE
Add ability to override / cancel transactions 

### ISSUE THREAD

**Issue by edhedges** [TrustWallet/trust-wallet-ios#197]
I’m not an expert on ETH transactions, but from what I’ve see online the ability to push a transaction through faster (by changing gas limit and/or price) or cancel a transaction (0 value from and to own address) require the ability to set the nonce value of the transaction, which looks to be missing functionality. Are there plans to add this feature in?

This was brought to my attention because I have a pending transaction, which I would like to either update / cancel, but I can’t at the moment and it’s been appearing/disappearing from etherscan and has just now shown in the trust UI after almost a day.

**Comment by michaelScoff** [comment]
Hey @edhedges! Overriding possible with Ethereum protocol, you can accomplish currently by creating a new transaction with the same `nonce`. 

I'm going to tackle pending transactions soon in the app, I will keep this in mind, to have the ability to resend transaction with a different configuration, if it's not confirmed.

**Comment by edhedges** [comment]
@michaelScoff Is there anything I can do that you know of, in the intermediary? I appreciate the app and it's been a valuable asset throughout my time in crypto.

**Comment by michaelScoff** [comment]
@edhedges can you reach out to me via telegram: vikmeup? let's see if we can work together on this.

**Comment by jamiew** [comment]
Is there currently any way to hide "failed" transactions? Ideally could resubmit with more gas etc, but at the very least I'd like to clear out old transactions so there's no more red badge

**Comment by vikmeup** [comment]
This problem should be addressed at the network level.

If you have stuck transactions you can always override with a custom nonce value: https://help.trustwalletapp.com/hc/en-us/articles/360004080194-Pending-Stuck-transactions
