### ISSUE TITLE
Ability to specify custom RPC Server

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#20]

**Comment by ozamihir1990** [comment]
Hi,
I added Ropsten RPC server in Config  
```
var rpcURL: URL {
        let urlString: String = {
            switch server {
            case .main: return "https://mainnet.infura.io/llyrtzQ3YhkdESt2Fzrk"
            case .kovan: return "https://kovan.infura.io/llyrtzQ3YhkdESt2Fzrk"
            case .oraclesTest: return "http://testnet.oracles.org:8545"
            case .ropsten: return "https://ropsten.infura.io/LWPCnS4dXhYMrcK7WaGI"
            }
        }()
        return URL(string: urlString)!
    }
    var remoteURL: URL {
        let urlString: String = {
            switch server {
            case .main: return "https://api.trustwalletapp.com"
            case .kovan: return "https://kovan.trustwalletapp.com"
            case .oraclesTest: return "https://oracles.trustwalletapp.com"
            case .ropsten: return "https://ropsten.etherscan.io"
            }
        }()
        return URL(string: urlString)!
    } 
``` 
But when I check wallet balance it shows **"Soemthing went wrong... Try again. "** in main screen
![screen shot 2017-11-29 at 3 42 52 pm](https://user-images.githubusercontent.com/12641767/33369934-102ff11c-d51c-11e7-982f-a48e75d56a96.png)

Am I doing anything wrong? Please guide me. I am new in Ethereum.

**Comment by michaelScoff** [comment]
Hey! 

You should be able to send transactions and see balance of your account, you might also see pending transactions 


If you want to see transactions you need to deploy this https://github.com/TrustWallet/trust-ray
It’s used to parse transactions on the chain and all the contracts data for ERC20 tokens and etc 

You can use Kovan network if you like, we have that service up and running for testing purposes. 

If you have any questions feel free to reach out via telegram: vikmeup

**Comment by michaelScoff** [comment]
Once you deploy trust-ray you need to change remoteURL to your endpoint.

**Comment by michaelScoff** [comment]
@ozamihir1990 yo! I just added custom ERC20 tokens in the iOS app, would you mind taking a look? telegram me as well

**Comment by michaelScoff** [comment]
Not relevant at the moment.
