### ISSUE TITLE
In add token allow user to scan QR code of contract address instead of just manual input

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#205]

**Comment by michaelScoff** [comment]
@James-Sangalli I'm working on it! Give me 5-10 minutes

**Comment by jmenhome** [comment]
Which data must be in QR code? Please write format

**Comment by vikmeup** [comment]
@jmenhome Actually all we need is to scan smart contract address. Then do RPC calls to fetch decimals, name and symbol

**Comment by jmenhome** [comment]
:) yesterday I open trust wallet, try to scan Token from QR, but only see changing camera output, nothing happens. Today I update app, current version: 1.5.40, and it work still not correct. After that I watch on address bar in my browser... it is IOs version, but my platform is Android.

Sorry, I will write issue on trust-wallet-android-source repository.

**Comment by vikmeup** [comment]
@jmenhome I have notified Android team about this bug.

@madcake @maratsubkhankulov

**Comment by jmenhome** [comment]
Thank you!
I create issue https://github.com/TrustWallet/trust-wallet-android-source/issues/12
