### ISSUE TITLE
Current balance not in visible areas on older iphones

### ISSUE THREAD

**Issue by colourful-land** [TrustWallet/trust-wallet-ios#206]
The screenshot is taken on iphone 4s. Despite being old, it seems reasonable to put information inside the content area.
![img_0003](https://user-images.githubusercontent.com/548435/34757902-5e95cc82-f628-11e7-891a-dfc032a2c15d.PNG)

**Comment by michaelScoff** [comment]
@colourful-land nice find! I can take a look at this.

**Comment by michaelScoff** [comment]
which iOS is this?

**Comment by colourful-land** [comment]
iOS 9.3.5:)

I feel that it's more because of screen estate.

**Comment by michaelScoff** [comment]
I think we can close this now, since we support iOS and higher
