### ISSUE TITLE
Token Name not shown 

### ISSUE THREAD

**Issue by andacaydin** [TrustWallet/trust-wallet-ios#208]
I just bought some tokens (0x10e9c804d5419237f390fa06189bea54279f438f) And they are shown in the wallet but unfortunately without the token Symbol (GIZA) although I typed it in in the "add token" form

**Comment by michaelScoff** [comment]
Can you try to add token again? This sounds very strange. Please attach a screnshot

**Comment by andacaydin** [comment]
Hello, I tried it again and it looks like this 👍 

![e35f91be-1131-4a4f-bdeb-8fe9dabd7bdd](https://user-images.githubusercontent.com/1972018/34839073-b093fcec-f700-11e7-8eeb-3b5a7fd2408e.png)
![ac401d90-7c93-450c-bf54-8332154582e3](https://user-images.githubusercontent.com/1972018/34839074-b0c7df94-f700-11e7-88b8-9fc933f7c3aa.png)

**Comment by andacaydin** [comment]
Its an iPhone X and the GIZA tokens can be seen for a second but then disappear

**Comment by michaelScoff** [comment]
@andacaydin I will take a token information when etherscan is up.

**Comment by andacaydin** [comment]
https://etherscan.io/address/0x10e9c804d5419237f390fa06189bea54279f438f

**Comment by michaelScoff** [comment]
@andacaydin https://etherscan.io/address/0x10e9c804d5419237f390fa06189bea54279f438f#code - can't really tell much from the contract, developers were lazy to upload ABI into etherscan

**Comment by andacaydin** [comment]
Okay but is there a way to give the token a Custom name? Right now its just showing nothing

**Comment by michaelScoff** [comment]
Yes, it's coming in the next builds! I would get a proper name from the smart contract of the ERC20 contract.

**Comment by michaelScoff** [comment]
On latest added both name and token name.
