### ISSUE TITLE
My wallet says I have no tokens

### ISSUE THREAD

**Issue by Chenae1313** [TrustWallet/trust-wallet-ios#211]
When I click on tokens, the app says I don't have any tokens, but I do.  I received LOCI tokens in three separate transactions and they all show up on Etherscan.  I don't see any place on the app that will let me add tokens manually either.

**Comment by michaelScoff** [comment]
Did you see message that says: + to add manually? Are you on the latest build?

**Comment by michaelScoff** [comment]
What’s your address? I can take a look

**Comment by Chenae1313** [comment]
No I didn't see a message that says I can add manually.  Maybe I have an older version of the app.  If I install a newer version will it wipe out records of my coins?  My address is:

0x5f65f499f33c928d726091ee83530ecb2adeefa6

Thank you!
Debra

**Comment by Chenae1313** [comment]
No I didn't see a message that says I can add manually. Maybe I have an older version of the app. If I install a newer version will it wipe out records of my coins? My address is:

0x5f65f499f33c928d726091ee83530ecb2adeefa6

Thank you!
Debra

**Comment by michaelScoff** [comment]
Update to the latest version! You should be fine, tokens should just appear for you. 

Make sure you have a backup saved, just for future!

**Comment by Chenae1313** [comment]
Great.... thank you!!!

**Comment by michaelScoff** [comment]
Did it work?

**Comment by Chenae1313** [comment]
I tried to install the new version of the app and they said my Apple I.D. password is not correct.  So, I’m going to try to re-set the password.

Debra

**Comment by Chenae1313** [comment]
Ok... I installed the update and clicked on the + and provided the info they asked for about LOCI coin.  Now my wallet shows only two of the transactions, but the total amount of tokens for all three transactions is correct.  There is no name next to the token amount.

Debra

**Comment by michaelScoff** [comment]
I can look into the name for the token, you should have new build out pretty soon. I’m glad you see correct amount at least

**Comment by Chenae1313** [comment]
The name of the coin is LOCI and their token contract address is:

 0x9c23d67aea7b95d80942e3836bcdf7e708a747c2

**Comment by Chenae1313** [comment]
The name of the coin is LOCI and their token contract address is:

0x9c23d67aea7b95d80942e3836bcdf7e708a747c2  



Thanks,

Debra

**Comment by anna64000** [comment]
I have everityng in community donate and can i widrawal

**Comment by michaelScoff** [comment]
Can you elaborate on this?

**Comment by michaelScoff** [comment]
Token coming in the next build. Closing this for now.
