### ISSUE TITLE
Locale settings for en_ro are bad

### ISSUE THREAD

**Issue by cachitu** [TrustWallet/trust-wallet-ios#212]
The currency format for tokens looks inconsystent on a device with eng language and romanian region locale (commas and dots are messed up). 1.000,0 is correct on the top total, while 3,5 tokens ar shown as 3.5. 31750 tokens are shown as 31.750. So is a bit confusing.

**Comment by michaelScoff** [comment]
@cachitu I can take a look, what's your public wallet address?

Also, do you have correct decimals set for the tokens?

**Comment by cachitu** [comment]
Hi Michael,
See below the screenshot, and at AGI tokens. The iPad one is en_ro while the iPhone is en_us.
Etherscan shows the tokens correct and I didn't set any decimals myself, the trust wallet detected them.
Ethereum Account 0x57F7f85C151A8A96CC20fEa6a43622334C335fe4 Info


| 
| 
|  | 
Ethereum Account 0x57F7f85C151A8A96CC20fEa6a43622334C335fe4 Info

etherscan.io

The Ethereum BlockChain Explorer, API and Analytics Platform
 |

 |

 |



I suspect you don't use the same formatting for total top label and tokens values labels.
    On Saturday, January 13, 2018, 8:40:48 PM GMT+2, Michael Scoff <notifications@github.com> wrote:  
 
 
@cachitu I can take a look, what's your public wallet address?

Also, do you have correct decimals set for the tokens?

**Comment by michaelScoff** [comment]
I can look at that as well in a few days. I will let you know progress on that unless you would like to help?

**Comment by michaelScoff** [comment]
@cachitu can you share screenshots?

**Comment by michaelScoff** [comment]
I'm closing this for now! Unless you provide more info
