### ISSUE TITLE
Gas limit

### ISSUE THREAD

**Issue by Andrylonga** [TrustWallet/trust-wallet-ios#214]
How could I get 600.000 as a gas limit? My limit is 300.000.

**Comment by michaelScoff** [comment]
@Andrylonga not at the moment, but we added support for set gas limit automatically, based on how much specific contract would require. If you have Xcode you can try that out right now from the `master`.

**Comment by michaelScoff** [comment]
Estimate gas limit has been implemented, so it will calculate correct amount + 20% automatically.
