### ISSUE TITLE
Ether stolen

### ISSUE THREAD

**Issue by Giusepp3** [TrustWallet/trust-wallet-ios#217]
I think there is a vulnerability because all of my ether was stolen.

**Comment by michaelScoff** [comment]
@Giusepp3 I would think that you exposed your private key/keystore to someone else. Are you sure you never gave up your private key to airdrops(which is a scam in most cases)? that's the most common mistake of the users.

What's your wallet address?

**Comment by Giusepp3** [comment]
I’ve never shown to anyone my private key... 

This is my address 

0x62d4e9858febfbea371dd57ad304cdbd484955ea

**Comment by michaelScoff** [comment]
Trust does not have the ability to export the private key, only keystore JSON. 
Where did you create a wallet? Where did you keep your backup or restore backup for your wallet?

**Comment by Giusepp3** [comment]
I create my wallet on myetherwallet.com and stored my json file on my mac

**Comment by michaelScoff** [comment]
@Giusepp3 There are few possible problems:
- you have keylogger/virus on your computer
- you used phishing website of myetherwallet.com and gave up your keystore JSON file + password?
Go check your history in the browser for this time: https://etherscan.io/tx/0xfb4eccbe2fbd0e259df6609ce6f2cc18b5626b4714afa69e6b6fe60fc9611891
I would expect if you entered phishing website they would take it all around that time. 

For the future! Try not to use the computer to access your wallet, it's not secure!
I highly recommend always to stick to mobile, there is not keyloggers or viruses. 

There is no way you can restore the funds, I assume someone has it now!  Which of this options do you think happened to you?

**Comment by Giusepp3** [comment]
I know that unfortunately is no way to restore funds... however i don’t think that i’ve had acces to a malicious website, i’ll check.  However now i’ve created a new wallet because this is compromised, i’ve used metamask with crome. Is this secure?

**Comment by michaelScoff** [comment]
Metamask itself is secure! but if you had keylogger/virus on your computer, you could easily lose that too. 

Make sure to find how it was exposed to someone else, before creating a new one, otherwise you could fall into the same trap. 

I'm closing this issue for now since it's not related to the Trust wallet.

**Comment by Kim-Taehwan** [comment]
I was also stolen ether. 
On iphone, use https://www.myetherwallet.com and trust wallet.
