### ISSUE TITLE
Unconfirmed transactions not shown

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#225]

**Comment by michaelScoff** [comment]
@James-Sangalli This is resolved on the master build now. Gonna be available in the App Store once approved by Apple.

**Comment by michaelScoff** [comment]
@James-Sangalli can you telegram me: vikmeup?

**Comment by James-Sangalli** [comment]
Nice!

**Comment by michaelScoff** [comment]
Just FYI it only shows up transactions sent from trust wallet, since RPC node not able to return pending transactions correctly.

Once you sent a transaction to the RPC, I place it into local storage and check status every 15 second or so, but at least it's visible to the user.
