### ISSUE TITLE
QR code page should acknowledge incoming transaction

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#226]

**Comment by michaelScoff** [comment]
@James-Sangalli what do you mean by this?

**Comment by James-Sangalli** [comment]
When a user opens up the qr code page there is no acknowledgement of an incoming transaction, this would be confusing to a noob.

**Comment by michaelScoff** [comment]
oh, you mean showing pop up if you receive new transaction?

**Comment by James-Sangalli** [comment]
Yes, otherwise people may be unsure they are actually receiving payment

**Comment by michaelScoff** [comment]
@colourful-land I got you. I will think about this UX wise. It's a problem that worth solving for sure.

**Comment by johnnynanjiang** [comment]
I had a look at this scenario on both iPhone and iPad, and would like to propose a couple of options as follows:

1. To display a toast message on top of the screen when the transaction is received while the QR code screen is still on.
2. Push notification.
3. Change 'Cancel' button to 'Close'.

**Comment by vikmeup** [comment]
@johnnynanjiang as a short solution we can rename to `Ok`. and then show alert view for received push notification?

**Comment by johnnynanjiang** [comment]
@vikmeup sounds good, I will give it a go.

**Comment by johnnynanjiang** [comment]
Given remote notification is coming soon, will hold and see how it can be utilized for this case.

**Comment by vikmeup** [comment]
@johnnynanjiang I would hold on this, notifications doesn't make any sense since transactions are slow and it won't give you fast response. It's pretty rare case that we don't want to tackle at the moment.

I will close this issue, since it wasn't reported by many users, our goal to focus on solving 80% use cases for the users!
