### ISSUE TITLE
Wallet creation

### ISSUE THREAD

**Issue by CrisESC93** [TrustWallet/trust-wallet-ios#229]
Hello guys!

I did start to read the code about the wallet creation and I have a doubt:

The creation of the private and public keys are offline (I mean you create the keys with SecKeyGeneratePair method) or use another method to create the keys I don't see?

Anyway, I hope can you help me and explain me please.

Thanks!!!

**Comment by michaelScoff** [comment]
Check out our Keystore lib: https://github.com/TrustWallet/trust-keystore
That’s handles creation of private key. 

@aleph7 can help on crypto stuff for Trust if you have more questions.

**Comment by CrisESC93** [comment]
Thanks @michaelScoff 

I will read the library.
