### ISSUE TITLE
Transactions on Kovan error even though they are successful 

### ISSUE THREAD

**Issue by tricdc** [TrustWallet/trust-wallet-ios#247]

**Comment by michaelScoff** [comment]
@tricdc Kovan network not being stable lately (infura being giving wrong data), can you try Robsten?

**Comment by michaelScoff** [comment]
@kolya182 can you take a look at Kovan node to see why it's returning error for transactions?

**Comment by kolya182** [comment]
@michaelScoff Will be fixed by end of the day

**Comment by michaelScoff** [comment]
@kolya182 is this still happening?
