### ISSUE TITLE
ERC20 token price issue 

### ISSUE THREAD

**Issue by Endro22** [TrustWallet/trust-wallet-ios#252]
My wallet says my 57000 ERC20 Tokens are worth 51k instead of $150

**Comment by michaelScoff** [comment]
Which tokens do you have? Symbol and contract name 

Pricing fetched from coinmarkercap

**Comment by Endro22** [comment]
https://etherscan.io/address/0x26d5bd2dfeda983ecd6c39899e69dae6431dffbb
Literally called ERC20...dont matter now, phone was restored and although I
backed it up, it looks like the keystone file never saved correctly in my
iCloud and I'm down 2 grand....I talked to Viktor about it.  I'm trying
restoration software now because I KNOW that I had that keystone file
downloaded. I'm stupid enough to only keep it in one place but not enough
to not back up the wallet at all.  If you have any good tips let me know

Thanks - Kyle

**Comment by michaelScoff** [comment]
I hope restoration software would help to get that Keystore JSON file back! 

I can close this issue for now then.
