### ISSUE TITLE
Remove QRCodeReaderViewController Dependency

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#268]
For security reasons.

**Comment by michaelScoff** [comment]
@MillerApps how much work is this involved?

**Comment by MillerApps** [comment]
To be honest I'm not sure, as I'm not 100% familiar with the codebase.

**Comment by michaelScoff** [comment]
Do you wanna take on this: https://github.com/TrustWallet/trust-wallet-ios/issues/123?

**Comment by MillerApps** [comment]
I can see what I can do in my free time. Any time constraints?

**Comment by michaelScoff** [comment]
The soon the better I think. How much free time do you have?

**Comment by MillerApps** [comment]
Not much, usually just Friday.

**Comment by MillerApps** [comment]
So you want to remove the QR-code functionality fully, or replace with another solution?

**Comment by michaelScoff** [comment]
We need to remove this as a dependency and have our own QR Scanner, if it's easy

**Comment by MillerApps** [comment]
Oh, I see. I can look into it but, I can't say how difficult it would be as I have never done anything with QR-Code reading. May I ask what the security issues were?

**Comment by michaelScoff** [comment]
Imagine that `QRCodeReaderViewController` being hacked and injected backdoor to send all the scanned values like the private key to their servers, that's a security flaw (because we could easily upgrade `QRCodeReaderViewController` and won't even know about), we need to make sure it's done by our code.

**Comment by MillerApps** [comment]
We could always use the source for QRCodeReaderViewController directly in the project and then maintain code ourselves. This would save time and provide a means of keeping the code secure.

**Comment by MillerApps** [comment]
@michaelScoff If this still needs to be done by someone I will have some extra free time this week at least until Thursday. Let me know if you would like a solution from scratch or to do as previously mentioned.
