### ISSUE TITLE
Build error due to trezor-crypto permissions

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-ios#269]
How to resolve? Or could you have an option to build w/o Trezor?

Installing TrezorCrypto (0.0.2)

[!] Error installing TrezorCrypto
[!] /usr/bin/git -C /var/folders/4_/9r8_0v5d1v7d5shvsw5mpvwr0000gp/T/d20180203-47306-1tcjziz submodule update --init --recursive

Submodule 'trezor-crypto' (git@github.com:trezor/trezor-crypto.git) registered for path 'trezor-crypto'
Cloning into '/private/var/folders/4_/9r8_0v5d1v7d5shvsw5mpvwr0000gp/T/d20180203-47306-1tcjziz/trezor-crypto'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by michaelScoff** [comment]
Are you planning to contribute to the iOS repo?

cc @aleph7

**Comment by Narragansett** [comment]
Hi!
I thought it through and there are two impediments … I primarily work in other disciplines so Ethereum is still just in the background for me, and on mobile I’m still back at Objective C and not nearly at a level to contribute in Swift. I’m afraid I’d be more of a distraction than a contributor. If I do dive into it my interests would also be different, more on the contracts side than the currency side so I’m working my way through Mist and Solidity. I am trying to learn (Swift and Ethereum) from what you’re doing if that’s permissble.
Thank you,
Jerry

**Comment by michaelScoff** [comment]
Jerry, can you reach out to me via telegram: vikmeup ?
I'm focused on bringing dapp browser into the play, I would need your help on that!

@aleph7 will take a look at this tomorrow.

**Comment by Narragansett** [comment]
Sure, contact me as Algonquin. I have Telegram fine on my iPhone account but I cannot find chat on Android, they only seem to have secret chat.

**Comment by michaelScoff** [comment]
Just press this link: https://t.me/vikmeup! I'm going to sleep at 6 am now, talk to you tomorrow.

**Comment by MillerApps** [comment]
I had the same issue creating a new SSH key and adding it to Github did the trick for me. 

[Guide on adding SSH](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

**Comment by Narragansett** [comment]
Great! That solved it (and now the error makes sense).
