### ISSUE TITLE
Incorrect custom coin binding

### ISSUE THREAD

**Issue by yumakemore** [TrustWallet/trust-wallet-ios#272]
The following coins are our custom coins. But Trust bind the with other coins of the same name. The address must be used instead of names: UET and DET from www.ultrashares.io

**Comment by yumakemore** [comment]
When I use UET or DET as the name and symbol of my own coin, Trust gets information (such as the ticker, price, currency) from another existing coin UET/DET that are different coins at different addresses.

**Comment by michaelScoff** [comment]
@yumakemore got it!

@kolya182 can you add these two address to exclude from the coinmarketcap prices?
https://github.com/TrustWallet/trust-ray

**Comment by yumakemore** [comment]
Thank you.
@kolya182, our coins are at www.ultrashares.io <http://www.ultrashares.io/> site.

CWC (Name: CWC; Symbol: CWC; Decimal=0; coin icon: www.ultrashares.io/coins/cw.png <http://www.ultrashares.io/coins/cw.png>):
0xDdCAf6c604592b37f775F3d303A02013BBD7AD93

UET (Name: UET; Symbol: UET; Decimal = 0; coin icon: www.ultrashares.io/coins/uet.png <http://www.ultrashares.io/coins/cw.png>):
0x4C54a332e3c962D5E513C3cc927c4cCf3452C79C

DET (Name: DET, Symbol: DET; Decimal=0; coin icon: www.ultrashares.io/coins/det.png <http://www.ultrashares.io/coins/cw.png>):
0xC8110527a0b803c0ba15456861d720864915b6ED

Currently, on Trust, our above UET and and DET are overlaid with information from other similarly named coins.

Please kindly let us know if you need any other information.

We, Ultrashares.io <http://ultrashares.io/> and Credit Washington, LLC would also like to see if we can initiate a customized Ultrashares Wallet powered by Trust so that people can easily use our coins.

—Ultrashares.io <http://ultrashares.io/> Team of Credit Washington, LLC

**Comment by kolya182** [comment]
@yumakemore coins have been added. I recommend to upload coin images in 256x256 pixels.

**Comment by michaelScoff** [comment]
@yumakemore could you update images with higher resolutions, here is a guide for you, will take 20 seconds: https://github.com/TrustWallet/tokens#add-custom-image

**Comment by yumakemore** [comment]
Thanks a lot. We updated/corrected our coin images as instructed.

**Comment by kolya182** [comment]
It's still old one http://www.ultrashares.io/coins/cw.png

**Comment by yumakemore** [comment]
I just uploaded corrected images to http://www.ultrashares.io/coins/cw.png <http://www.ultrashares.io/coins/cw.png> (and uet.png and det.png under the same dir) and also placed a pull request on the github site as instructed. Thank you again. We really appreciate this prompt help.

**Comment by yumakemore** [comment]
The problem reappeared today.
Please kindly take a look at the attach screenshot.
CWC, UET, and DET are our coins. The tickers are expected to be “0 —“ just like CWC.
Also, their icons are incorrect (especially, UET image is from some other coin). 
I uploaded new 256x256 images at both the github (pull request as instructed) and www.ultrashares.io/coins/cw.png <http://www.ultrashares.io/coins/cw.png>, uet.png, and det.png.
I also changed all addresses to lowercase as instructed.

**Comment by yumakemore** [comment]
The problem reappeared today.
Please kindly take a look at the attach screenshot.
CWC, UET, and DET are our coins. The tickers are expected to be “0 —“ just like CWC.
Also, their icons are incorrect (especially, UET image is from some other coin). 
I uploaded new 256x256 images at both the github (pull request as instructed) and www.ultrashares.io/coins/cw.png <http://www.ultrashares.io/coins/cw.png>, uet.png, and det.png.
I also changed all addresses to lowercase as instructed.
