### ISSUE TITLE
Contacts list to retrieve wallet address(es)

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-ios#277]
Would this be accepted? User would store friends wallet addrs in contacts list, suggesting the notes section,  use the contact name to retrieve wallet. Contact could have multiple wallets, etc.

![01 contacts](https://user-images.githubusercontent.com/4932861/35783433-dd40bc44-09d4-11e8-84df-30517f3bafc9.PNG)
![02 contacts](https://user-images.githubusercontent.com/4932861/35783434-e01642b8-09d4-11e8-9f22-c0953721adc5.PNG)
![03 contacts](https://user-images.githubusercontent.com/4932861/35783474-c7f5e9a8-09d5-11e8-941b-d28dc5aabd32.PNG)

**Comment by michaelScoff** [comment]
@Narragansett check out this issue: https://github.com/TrustWallet/trust-wallet-ios/issues/174, I think it's the best solution so far.

Also regarding actions, I have an idea to keep it this way:

Row: Paste / Contact / QR Code
Row: Receipt Address 

For the paste action, we gonna keep `Paste` label, it is much more intuitive that way.

Can you implement contact fetching functionality? and add contact icon for now!

**Comment by Narragansett** [comment]
i implemented happy path today, I have to implement error handling, multiple wallets, etc. Contact notes section is best we can use for this. Contacts have custom fields but they're pre-set for traditional items.I will revert Paste to text.

**Comment by vikmeup** [comment]
Dup of: https://github.com/TrustWallet/trust-wallet-ios/issues/277
