### ISSUE TITLE
Display problem with contract having multiple transactions

### ISSUE THREAD

**Issue by victorengel** [TrustWallet/trust-wallet-ios#281]
Example is txn 0xe4f904f59091a7407322dec5e6f1215f817ae64aa4c54c2668504f45ae33a425. In this case, 1 ETH was sent and the contract created a return transaction of 740 CPY. Trust wallet captured the return 740 tokens, but for the outgoing transaction, it is displaying -740 CPY instead of -1 ETH.

**Comment by vikmeup** [comment]
This should be fixed now.

**Comment by victorengel** [comment]
now the incoming tokens show, but the outgoing ETH is not showing at all. In Telegram you said, "I'm working on few design changes to see all the operations for specific transaction." Is there a branch for that?
