### ISSUE TITLE
DigixDAO tokens (DGD) do not appear in wallet

### ISSUE THREAD

**Issue by raggousis** [TrustWallet/trust-wallet-ios#282]
DigixDAO tokens (DGD) do not appear automatically and the contract must be manually added.  The balance shows after the contract is manually added.

Also related, the DGD transactions do not show up in the transactions tab.  I've only attempted a receive.

This is an ERC20 compatible token that's been around for a while.  Should it be expected that tokens like these would show up automatically?

Thanks!

**Comment by michaelScoff** [comment]
@raggousis Most tokens show up automatically, there is a case when it’s not parsed from the blockchain properly, but we are improving this in the next build, you should be good in a few days. 

Manually adding should be working as expected. 💪

**Comment by anna64000** [comment]
But howe put out?

**Comment by anna64000** [comment]
But howe put out?

**Comment by vikmeup** [comment]
This should be fixed now
