### ISSUE TITLE
Simple Token (ST) does not show price

### ISSUE THREAD

**Issue by raggousis** [TrustWallet/trust-wallet-ios#283]
Simple Token does not show a token price.

It may be related to an issue with the symbol.  The contract seems to be labeled "ST" as here:
https://etherscan.io/token/0x2c4e8f2d746113d0696ce89b35f0d8bf88e0aeca

But coinmarketcap has it as "OST":
https://coinmarketcap.com/currencies/simple-token/

Attempting to add the contract manually, with a new "OST" symbol does not work.

Thanks!

**Comment by michaelScoff** [comment]
@raggousis @kolya182 can you take a look at this to make sure we have correct mapping for this token?

**Comment by michaelScoff** [comment]
This PR should fix it: https://github.com/TrustWallet/trust-ray/pull/162
