### ISSUE TITLE
iOS app locks up after screen goes to sleep

### ISSUE THREAD

**Issue by raggousis** [TrustWallet/trust-wallet-ios#284]
If TrustWallet is in the foreground when the screen goes to sleep, and the screen is off for more than a few seconds, then when logging into the phone again, the trust app will seem hung, and crash after some time.

- iPhone X, Face ID enabled
- Passcode / Touch ID is on
- Does not seem to matter what screen it is on.
- iOS 11.2.5

**Comment by michaelScoff** [comment]
@raggousis Thanks for reporting! Master already has this fix, I just pushed new build to the iTunes connect, hopefully it will be approved tomorrow.
