### ISSUE TITLE
Token import does not auto populate fields

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#285]
As above, are you guys planning to include this feature? i.e. you scan or input a contract address and it queries the name, symbol, decimals etc.

If so then when? 

Thanks

**Comment by michaelScoff** [comment]
Which QR codes have support for that?

**Comment by James-Sangalli** [comment]
Can query a server for that information, not from the QR code

**Comment by michaelScoff** [comment]
@James-Sangalli That’s coming in a few weeks, we can query RPC easily. 

Another alternative to have a list of all the tokens locally and you just enable them.

**Comment by vikmeup** [comment]
Implemented on master
