### ISSUE TITLE
Handle command and dot for input values.

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#296]
If you are using UK keyboard you won't be able to use `.`, or if in US then `,`.
We need to have a parser that will try to parse locale if that fails, try different ways.

Let's create separate parser that we could test.

![2018-02-07 12 33 52](https://user-images.githubusercontent.com/32179653/35940186-2cda9fce-0c03-11e8-95f2-57d7c5cfd794.jpg)

**Comment by OlegGordiichuk** [comment]
This issue should be done with usage of NSNumberFormatter and do not forget to set  NSLocale.currentLocale(). 

Simple tutorial: https://supereasyapps.com/blog/2016/2/8/how-to-use-nsnumberformatter-in-swift-to-make-currency-numbers-easy-to-read

**Comment by michaelScoff** [comment]
@OlegGordiichuk we use correct locale to parse values, but some users copy paste values and fail on this, as you can see in this example. Keyboard has `,` but user used `.`
