### ISSUE TITLE
Very scary bug. 

### ISSUE THREAD

**Issue by Bleedingsmurf** [TrustWallet/trust-wallet-ios#306]
I seen a spider on my moniter today.. it was a dark brown with a couple lighter brown stripes on the top. The legs were about 2cm in length. I think it was very poisonous. The look it gave me as it was crawling across a million pixels still haunts me.. it wanted my soul... my flesh.. my everything.

**Comment by vikmeup** [comment]
🤔

**Comment by MillerApps** [comment]
I'm sorry sir but, that is not the type of bug you would report here. Please try to[ bug reports](https://usersnap.com/blog/what-is-a-bug-report/) about Trust Wallet. Thank You!

**Comment by michaelScoff** [comment]
This is the funniest issue so far 😄
