### ISSUE TITLE
No profile for team

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#319]
No profile for team '9873B38DWV' matching 'match AppStore com.sixdays.trust' found:  Xcode couldn't find any provisioning profiles matching '9873B38DWV/match AppStore com.sixdays.trust'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

How to get the profile so it can be built on a physical iPhone? Cheers

**Comment by hewigovens** [comment]
Do you have your own apple developer account?

**Comment by hewigovens** [comment]
@James-Sangalli You should able to build it for iOS Simulator

**Comment by James-Sangalli** [comment]
No other way to build it on physical phone? I have a simulator but I need a physical build also

**Comment by mishfit** [comment]
This might help, however it's probably better to just wait: https://blog.ionicframework.com/deploying-to-a-device-without-an-apple-developer-account/

**Comment by James-Sangalli** [comment]
Sussed now, thanks.
