### ISSUE TITLE
Can not sent DEB and EEE tokens

### ISSUE THREAD

**Issue by aycanurun** [TrustWallet/trust-wallet-ios#322]
its deletes last 3 digits when trying to send deb and eee tokens to mew wallet address and fails transfer

**Comment by vikmeup** [comment]
@aycanurun can you give more information? 

What's the smart contract address? Can you provide screenshot or video of this bug?

**Comment by aycanurun** [comment]
I checked again, not deleting last 3 digit
My send address is
0x151202C9c18e495656f372281F493EB7698961D5
But in history shows to
0x151202C9c18e495656f372281F493EB7698961D5

Ios

**Comment by aycanurun** [comment]
Sorry my sent address is
0xCCde161a2cCD522b05C536e45B263FBbeaaC5580

**Comment by aycanurun** [comment]
Transaction id
0x16ced4538765535aa751e59d5e594cfeff8f8d2e5bff47c2cbcffbe57ca5d1b2

**Comment by vikmeup** [comment]
As you can see in here all transactions fails: https://etherscan.io/address/0x151202c9c18e495656f372281f493eb7698961d5

**Comment by vikmeup** [comment]
You need contact the owner of the smart contract regarding this issue, it's not just you, I believe it's not related to the Trust wallet itself.

**Comment by aycanurun** [comment]
Successfuly sent ETH and TEL tokens but when trying to sent DEB or EEE receiver addrress showing wrong also fails to sent

**Comment by vikmeup** [comment]
can you reach out via telegram: vikmeup?

**Comment by aycanurun** [comment]
its sent to address,
0x151202C9c18e495656f372281F493EB7698961D5 which im not entered

**Comment by vikmeup** [comment]
Tokens freezed on the smart contract, you need to contract owner of the smart contract directly.
