### ISSUE TITLE
Move JS code into trust-web3-provider

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#337]
https://github.com/TrustWallet/trust-wallet-ios/tree/master/JS (used to inject trust web3 provider into the browser) code has to be moved into https://github.com/TrustWallet/trust-web3-provider to be reused for both iOS and Android.

What's the best way to accomplish that? So it's easy to pull the latest code (https://github.com/TrustWallet/trust-wallet-ios/blob/master/JS/dist/trust-min.js) into the project.

**Comment by hewigovens** [comment]
npm or cocoapod + gradle / maven?

**Comment by vikmeup** [comment]
Now iOS moved into https://github.com/TrustWallet/trust-web3-provider
