### ISSUE TITLE
DCN $ amount does not show up, trouble sending out

### ISSUE THREAD

**Issue by siberiangirl** [TrustWallet/trust-wallet-ios#338]
No problem importing my DCN, token shows up but no corresponding $ amount showed up as it did under my TRON import. Perhaps because price of DCN is less than $ 0.01?  Then would not let me transfer out due to insufficient funds which I had to cover gas.
Thanks for your help in this matter. Great App!

**Comment by kolya182** [comment]
@siberiangirl Can you send screenshots of imported token and info on how much you trying to send ?.

**Comment by vikmeup** [comment]
You need ETH to pay for a gas fee in order to send transaction.
