### ISSUE TITLE
Sending ETH

### ISSUE THREAD

**Issue by Philippmattheis** [TrustWallet/trust-wallet-ios#34]
Hey,
i just downloaded the App, and transfered some ETH to the wallet. unfortunately, I can’t send them to another adress now. There is either an error or it sends tiny amounts. Thought about changing the gas level, but couldn’t find it in the settings. Help is highly appreciated. 

Thanks,
Philipp

**Comment by michaelScoff** [comment]
Hey @Philippmattheis, once you entered amount you should be able to see `Advance Configuration` option, which will allow you to set transaction fee: `Fast`, `Regular`. 

https://github.com/TrustWallet/trust-wallet-ios/blob/cee6e67e5ca26c13730b98c9a1379c68c9880ccf/Trust/Transactions/Types/TransactionCost.swift#L11

This is default `gasPrice` for those options. Do you want to set gas price manually?

**Comment by michaelScoff** [comment]
@Philippmattheis there is a few features I was going to build for the next release:
Display transaction fee preview: https://github.com/TrustWallet/trust-wallet-ios/issues/35
Allow to set custom gasPrice: https://github.com/TrustWallet/trust-wallet-ios/issues/36

Is that what you are looking for in this app? Please let me know

**Comment by Philippmattheis** [comment]
Hi Michael, thanks for the quick reply! Problem is: Even when I put the transaction speed to "fast", I get an Error
[error.pdf](https://github.com/TrustWallet/trust-wallet-ios/files/1354888/error.pdf)
Can you help?
Thanks!

**Comment by michaelScoff** [comment]
@Philippmattheis have you tried to put `3.98` with a dot instead? 

In the new build that's coming up in a few days, it will show specific error that's triggered by RPC server.

**Comment by Philippmattheis** [comment]
Hi Michael,
ahh - relieve! It just worked. 
For your feedback: I can't use a dot, my keyboard (iphone7/Europe) shows only komma, no dot.

**Comment by michaelScoff** [comment]
@Philippmattheis thank you for reporting this bug! Created separate issue to track it down: 
https://github.com/TrustWallet/trust-wallet-ios/issues/38 for the next release.

Thank you for trying out early version of Trust Wallet. It's very early in development, 3 weeks old! Just got basic functionality in place, and going to work on polishing and making things flawless for users!

Feel free to report any feedback/bugs you find.

**Comment by Philippmattheis** [comment]
Hi Michael,
actually I was a bit naive to download and use it. In the App Store it looked like a tested version. Anyway, thanks a lot for the quick support and good luck with it!

Cheers

Philipp

**Comment by michaelScoff** [comment]
@Philippmattheis would you mind leaving App Store review as well? Thank you again!

**Comment by Philippmattheis** [comment]
Hi Michael,
I'd like to give you a good review. However, at the moment, I still can't send the rest of my ETH-amount. It works with full numbers, but with 0.99 etc. At the moment I am stuck with 0.995 ETH on your wallet and can't get them out. I have an European iPhone, there is no option to replace the ',' with '.'. What can I do?

Thanks!

**Comment by vikmeup** [comment]
@Philippmattheis there is a few things you can do:
1) You can make a note in the Notes app with `0.995` and copy paste that, make sure to take out gasPrice.
2) Wait until new build is out, I just submitted to the App Store, ~1-2 until it's available for everyone.

**Comment by michaelScoff** [comment]
@Philippmattheis new build is out on the App Store, try it out!
