### ISSUE TITLE
scan is not working

### ISSUE THREAD

**Issue by shenghsi** [TrustWallet/trust-wallet-ios#352]

**Comment by vikmeup** [comment]
@shenghsi can you elaborate on this?

**Comment by shenghsi** [comment]
I am on iphone 8 with ios 11.2.5
Select send, and tap the bar code to scan, then it shows as
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3663436/36296781-e6aba5c8-12a3-11e8-8102-41573a09ef99.png">

**Comment by vikmeup** [comment]
You need to give access to the camera, I bet you disabled it. Please check settings.

**Comment by shenghsi** [comment]
You are right.
