### ISSUE TITLE
Implement 712 standard

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#368]
https://github.com/ethereum/EIPs/pull/712

**Comment by vikmeup** [comment]
@mishfit can you take a look at this?

**Comment by mishfit** [comment]
Yeah, I actually need this too! What a coincidence!

**Comment by mishfit** [comment]
Before implementing this I need to finish adding [a "sandbox" to the dapps browser](https://github.com/TrustWallet/dapps-browser/pull/2)

**Comment by vikmeup** [comment]
@mishfit do you have any estimates for 721?
