### ISSUE TITLE
My ethereum has gone

### ISSUE THREAD

**Issue by cccl10** [TrustWallet/trust-wallet-ios#370]
Hello I need help to find out why my ethereum has gone out my wallet to by verge and it’s not in over wallet where is it

**Comment by vikmeup** [comment]
@cccl10 can you provide more information so I can help you debug this?

**Comment by vikmeup** [comment]
Also:
1) Where did you store your backup?
2) Did you ever give your backup to anyone?
3) Did you ever participate in airdrop that needed your private information?
4) What's your wallet address?

**Comment by vikmeup** [comment]
@cccl10 let me know more information, for now, I'm gonna close this issue.

**Comment by cccl10** [comment]
Can you please find my ethereum

**Comment by vikmeup** [comment]
Can you provide information listed above? Trust does not store any private information on the servers.

**Comment by vikmeup** [comment]
Let me know if you need help!
