### ISSUE TITLE
Browser does not redirect

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#402]
https://originalcryptocoin.com/airdrop/ on this page if you press get tokens it’s not redirecting to the page somehow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
Noticed this issue with different websites as well.

**Comment by hewigovens** [comment]
We need to conform to `WKUIDelegate` and implement `webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView?`

**Comment by vikmeup** [comment]
@hewigovens that sound easy, can you get this fix in?
