### ISSUE TITLE
Token incorrectly has fiat currency value

### ISSUE THREAD

**Issue by Amphitryon** [TrustWallet/trust-wallet-ios#405]
## Your Environment

* Version used:
* Operating System and version (iOS or Android):

**Comment by vikmeup** [comment]
@Amphitryon can you provide more information so we can help?

**Comment by Amphitryon** [comment]
![trust wallet](https://user-images.githubusercontent.com/36480488/36722176-cfa26966-1ba4-11e8-8ece-6a4e2b0ac49f.jpg)

**Comment by Amphitryon** [comment]
Hi - the GEO coins should just be tokens with no actual value but the wallet seems to have given a value

thanks

**Comment by Amphitryon** [comment]
using IOS

**Comment by vikmeup** [comment]
Can you provide contract address to GEO token? We can exclude from matching with coinmarkercap tokens

**Comment by Amphitryon** [comment]
0x42901532700341c0B26854FA7C0edA1a66F1158E

many thanks

**Comment by Amphitryon** [comment]
Many thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
