### ISSUE TITLE
Display insufficient balance

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-ios#407]
On transaction confirmation page `insufficient ethers` should reflect network symbol of current network:
Example for POA: `insufficient POA balance`
Example for ETH: `insufficient ETH balance`

**Comment by michaelScoff** [comment]
@kolya182 For tokens it should same the same. Insufficient VIKTOR token balance

**Comment by vikmeup** [comment]
@hewigovens what do you think? I think this is pretty intuitive for the user.

Ether: `Insufficient {symbol} balance` => `Insufficient POA balance`
Ether Gas Fee `Insufficient {symbol} to cover gas fee` => `Insufficient ETH balance to cover gas fee`
Token: `Insufficient {symbol} token balance` => `Insufficient POLY token balance`

`Insufficient ETH balance to cover gas fee` - this one might be little long, but it's good for newcomers, can you make sure this title visible to small devices?

**Comment by hewigovens** [comment]
Okay
