### ISSUE TITLE
iPhone SE scrolling issues

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/trust-wallet-ios#411]
Import Wallet
<img width="432" alt="screen shot 2018-02-27 at 10 49 23" src="https://user-images.githubusercontent.com/360470/36709546-5fcbb282-1bb3-11e8-87f4-109fffb42640.png">

Confirm
<img width="432" alt="screen shot 2018-02-27 at 10 52 13" src="https://user-images.githubusercontent.com/360470/36709547-602481fa-1bb3-11e8-8ad4-c73cb3baa800.png">

**Comment by VKoskiv** [comment]
I'll take a look.

**Comment by vikmeup** [comment]
@VKoskiv thanks! I was thinking to simplify this
1) combine gas limit and gas price into one row?
2) Combine Max total: amount + network fee ? otherwise this view looks too long for the regular user.

I would look into Meta Mask and Toshi for inspiration

**Comment by vikmeup** [comment]
This is fixed now
