### ISSUE TITLE
Show blockies for wallets/transfers

### ISSUE THREAD

**Issue by aleph7** [TrustWallet/trust-wallet-ios#412]
The Mist Ethereum wallet shows an unique image for each address. This helps identify accounts. It uses this blockies implementation: https://github.com/ethereum/blockies

## Expected Behavior
When you enter an address in the transfer screen the blockie should appear. The blockie should match the one shown in Mist.

The list of wallets should have a blockie for each wallet.

## Current Behavior
No images.

**Comment by vikmeup** [comment]
I personally don’t like those icons, they look nerdy and not very intuitive to regular person, works for developers tho. 

First step to identity wallet was adding balance to the wallet. 
Next is BIP39 which will let you know index of the wallet. 
Then we gonna add ability to name it 💪


Is it possible to include name of the wallet to Keystore? Even tho it’s not part of the spec

**Comment by aleph7** [comment]
Should we come up with a nicer looking version of it? I agree that they are weird, but it would be nice to have a visual representation.

**Comment by aleph7** [comment]
As for adding a name: let's do it. Is there a ticket?

**Comment by vikmeup** [comment]
@aleph7 yes, I would be down for something nice looking!

Also for the wallet name: https://github.com/TrustWallet/trust-wallet-ios/issues/40. We are waiting for some changes on web3Swift, once that's done ENS will be integrated! This would be sick as well in the wallets list

**Comment by aleph7** [comment]
Do like the GitHub style? https://github.com/blog/1586-identicons there is also https://jdenticon.com/#icon- or we can come up with something different. I like only having one color per icon.

**Comment by vikmeup** [comment]
@aleph7 I like JDENTICON, those look much better!

**Comment by MillerApps** [comment]
@vikmeup and @aleph7 did you see this? https://github.com/Boilertalk/BlockiesSwift 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aleph7** [comment]
Nice, but Jdenticons are so much nicer. https://github.com/aleph7/jdenticon-swift

**Comment by MillerApps** [comment]
Nice work! I agree, they look like elegant.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
