### ISSUE TITLE
Confused between prices of 2 tokens using same Symbol

### ISSUE THREAD

**Issue by tonybka** [TrustWallet/trust-wallet-ios#414]
Example:
_CANDY_ coin and _CandyHCoin_ is different crypto currencies using same Symbol CANDY. After added _CandyHCoin_ into Trust wallet, our wallet app was using _CANDY_'s price to display.

Detail:
_CANDY_ **(Available on CMC)**  https://coinmarketcap.com/currencies/candy/ 
Meanwhile
_CandyHCoin_ **Not Listed any Exchange:**: https://etherscan.io/token/0x45555629aabfea138ead1c1e5f2ac3cce2add830?a=

**Comment by kolya182** [comment]
This PR should fix your issue.

**Comment by tonybka** [comment]
Sorry @kolya182 if you mind but i didn't PR for that dummy currency. I was using this such dummy token for testing while working on our project.
