### ISSUE TITLE
Consider presenting a warning/notification when switching to testnets.

### ISSUE THREAD

**Issue by VKoskiv** [TrustWallet/trust-wallet-ios#438]
Currently, switching to testnets in Trust is absolutely trivial. Three taps from the main screen.
I feel this presents a social engineering attack vector. Something like the following:

>Malicious buyer: "Okay, to receive my ether, you need to switch to the ropsten network, because [Insert convincing reason here, technical jargon]"
>Seller: "Okay."
Seller switches to a testnet, and receives his payment as normal. (Looks identical to a normal ETH transaction)

This is obvious to us technical people, but Trust is built with safety in mind. So I propose the following:

- A) We add a 'Developer Mode' toggle, and hide the testnets unless `Developer Mode` is enabled.
- B) We show a popup warning on the first time a user switches to a testnet, explaining what testnets are for.

**Comment by MillerApps** [comment]
Good idea!

**Comment by vikmeup** [comment]
That's a possible vector of attack, totally! There are a few things to keep in mind, I haven't heard any cases. I hope users won't be trusting other parties to make such transactions at all! 

I would suggest having a warning for the first time user switch test network as you described in `B`

`Developer Mode` will add additional code complexity to the code and use of the app atm, looking for short cuts.

**Comment by johnnynanjiang** [comment]
I'm working on it and will raise a PR soon @vikmeup

**Comment by vikmeup** [comment]
@johnnynanjiang oh cool! I think just showing alert for the first time is all we need at the moment.

Also, sync up with @VKoskiv, he was going to work on custom nodes.

**Comment by vikmeup** [comment]
This should be fixed now
