### ISSUE TITLE
See password on backup page

### ISSUE THREAD

**Issue by CruiseMan** [TrustWallet/trust-wallet-ios#467]
I would like to see entered password on backup page.
Something like:
<img width="293" alt="screenshot 2018-03-12 12 56 45" src="https://user-images.githubusercontent.com/15807643/37306413-e414862c-25f4-11e8-9583-c46065ef315b.png">

**Comment by vikmeup** [comment]
Consider: https://github.com/EurekaCommunity/GenericPasswordRow

**Comment by vikmeup** [comment]
Not needed
