### ISSUE TITLE
Full support bytes type / big ints in string for 712

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#474]
Based on https://github.com/TrustWallet/trust-wallet-ios/pull/450

**Comment by alejandro-isaza** [comment]
Reference docs: http://solidity.readthedocs.io/en/develop/abi-spec.html#basic-design

**Comment by vikmeup** [comment]
@alejandro-isaza @hewigovens I think [web3swift](https://github.com/BANKEX/web3swift) has this implemented already. We are going to use this lib, does it make sense to bring now?

**Comment by alejandro-isaza** [comment]
I'd rather implement it in Swift, but that's just me :)

**Comment by hewigovens** [comment]
What we implemented now is a subset of solidity types, specifically, represented by JSON values. Because we receive data from DApp Browser (web3.js) and we only support bytes by hex strings.

**Comment by alejandro-isaza** [comment]
Now TrustCore has ABI encoding, what else are we missing for this?

**Comment by vikmeup** [comment]
@alejandro-isaza I bet we just need to adapt it to use inside Trust app, can you take a look? 

Btw, that stuff looks great!

**Comment by hewigovens** [comment]
@alejandro-isaza After encoding, ABIValue (.uint, .int, .bool) data length is fixed (32), EIP 712 encoding for this types are compact / variable. It seems that we can't simply replace with TrustCore(ABIValue)?
