### ISSUE TITLE
Improve progress bar visibility

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#477]
The progress bar on browser have the same color as a navigation bar, makes it hard to see.

**Comment by MillerApps** [comment]
I may be mistaken but I don't think you can change the progress bar color of an SFSfariViewController. http://www.openradar.me/22497026

**Comment by vikmeup** [comment]
This is for DApp Browser! we have progress bar in it.

**Comment by MillerApps** [comment]
Oh, yeah that doesn't use the SFSfariViewController.
