### ISSUE TITLE
Can you explain how does trust.js work with web3.js?

### ISSUE THREAD

**Issue by sskeater** [TrustWallet/trust-wallet-ios#506]
I note that when cryptokitties start a transaction to blockchain, we can see the confirm dialog about 'from', 'to', 'gas limit' and so on. I want to know how to call this dialog when I start a transaction from my contract.

If I open the url with chrome but not in "Trust app", how to call the confirm dialog about transaction? Is it supported by "trust.js"? Or I should implements it myself? And how to implement it.
Thanks.

**Comment by vikmeup** [comment]
The call has been triggered by the provider: https://github.com/TrustWallet/trust-web3-provider. You can explore how it's all hooked up in the Browser functionality
