### ISSUE TITLE
Pre-check if ETH address exist on blockchain. 

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-ios#51]
Can be done while the user enters the amount to send. 
As a result of the check, warning message something like (1. You are sending ETH to address that doesn't have any public transaction on blockchain yet or 2. Double check wallet address) in case of not finding the address on the blockchain. It can prevent the user from sending to not existing address in some cases.

**Comment by michaelScoff** [comment]
This is long terms feature that we could add, I will close this for now.
