### ISSUE TITLE
Spelling error in /Wallet/ViewModels/EnterPasswordViewModel.swift

### ISSUE THREAD

**Issue by NickSet** [TrustWallet/trust-wallet-ios#513]
The value parameter on line 12 should be "Password used to encrypt your backup file to keep it secure!" instead of "Password used to encrypt you backup file to keep it secure!"

I'd be happy to start a pull request and fix this minor typo.

**Comment by vikmeup** [comment]
Thanks for finding it!

Updated on Localize, it should be pulled into next release automatically.

Localization available in here: https://lokalise.co/signup/3947163159df13df851b51.98101647/all/

**Comment by vikmeup** [comment]
Done: https://github.com/TrustWallet/trust-wallet-ios/commit/13d0bf1e5b40a6582e6cb2e7e583a1981d22ff2b
