### ISSUE TITLE
Slight delay when press on wallet

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#514]
If you press on `Wallets` cell from the settings, it has a small delay(0.1-0.3s), I wonder why. 

@alejandro-isaza can you take a look? wonder if it's a keystore returning wallets slowly or images loading for too long?

**Comment by alejandro-isaza** [comment]
Likely wallets being loaded (maybe decrypted too). I'll have a look.

**Comment by alejandro-isaza** [comment]
Part 1 of 2: https://github.com/TrustWallet/trust-keystore/pull/34
