### ISSUE TITLE
DApp bookmarks crashes on master

### ISSUE THREAD

**Issue by MillerApps** [TrustWallet/trust-wallet-ios#532]
The app crashes when trying to open bookmarks. @VKoskiv can you take a look?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
on master? or on the App Store build?

**Comment by MillerApps** [comment]
On master

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MillerApps** [comment]
I think it’s a Realm migration issue. I just reset my simulator and the problem is gone. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MillerApps** [comment]
@vikmeup you fixed this correct?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
Yes, this is fixed now
