### ISSUE TITLE
Trust Java script problem

### ISSUE THREAD

**Issue by Blackpalms** [TrustWallet/trust-wallet-ios#534]
Good morning Sir/Madam
When I try to sent back to gate.io my TNT cryptocurrency, the same address it came from in the first place ( because I can’t sell on bancor, no TNT) I get this message!
The operation couldn’t be 
completed. (Javascript-kit.JSErrorDomain error 1.) 

Kind regards from Holland. 

Marcel Schoo

**Comment by vikmeup** [comment]
Can you provide a smart contract to `TNT`? Can you provide a screenshot as well?

**Comment by Blackpalms** [comment]
Good morning Vikmeup all the cryptos from gate.io deposit the same problem but it look now i get it don. 
I have a screenshot from the first message how i can place it here? 

Thanks for fast response and help

**Comment by Blackpalms** [comment]
I am not a computer expert I give myself a 6 .-) 
Some html and some flash in the past. 
Most things i understand but no idea how smart contracts working

**Comment by Blackpalms** [comment]
0x1ac6d3d4f7d3ab7ff171bd164e37ce55e4810e78bf8432187c0af28fffdd738b 

The Hash

Still busy but no java script problem it seams

**Comment by vikmeup** [comment]
Oh, nice! let me know if this happens again

**Comment by Blackpalms** [comment]
Thank dear Vikmeup great 👍🏻 help, the crypto arrived on gate io.
I really don’t understand what go wrong I scan the address from laptop with my iphone couple times and control the code. 

Have a nice day. 
( for next time how i place a screenshot here ) 
This was my forst post after write in.

**Comment by Blackpalms** [comment]
Forst = First 😊

**Comment by vikmeup** [comment]
Nice!
