### ISSUE TITLE
No prices shown, one transaction from Index not arrived. 

### ISSUE THREAD

**Issue by Blackpalms** [TrustWallet/trust-wallet-ios#538]
The whole day prices not shown in my app, only a couple time’s, also sent some funds from Index too my wallet but still not arrived also not shown by my transactions this the first time. 
Other transactions made arrived today without problem even with no prices shown between. 
I start too not trusting this app from Trust. 🤢

**Comment by Blackpalms** [comment]
Funds shown again and ncash arrived, but still worried why this happening al the time. 
(No wifi problem, because same problem on mobil subscription, no problems in other apps)

**Comment by vikmeup** [comment]
Hey. Can you provide tokens that you don’t have prices to? Trust getting prices from coinmarkercap. 

Can you provide screenshots and let’s get this fixed! We haven’t seen many issues reported as you mentioned! 

You can reach out to me via telegram directly: vikmeup

**Comment by Blackpalms** [comment]
Thanks Vik I go to telegram now

**Comment by vikmeup** [comment]
Nice! Thanks for reaching out to telegram! This should be fixed/improved in the next build.

Closing this for now.
