### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by BifocalComb** [TrustWallet/trust-wallet-ios#55]
Transaction 0xf0cad610c300324b9e192ee3fd431d7acfcfb9a758a23bfa6865b51efc6dbfae 
Sent 3.9 OMG, an ERC20 token to my address. It hasn't shown up after 80 confirmations.

**Comment by michaelScoff** [comment]
Hey @BifocalComb. I can see that you transfers tokens to this address: https://etherscan.io/token/OmiseGo?a=0x24cc2359bc42b2c855678c7fae8efbb3a7d3660c

For tokens we currently using **ethplorer.io** API to get tokens information, it's returning 0 :(
https://api.ethplorer.io/getAddressInfo/0x24cc2359bc42b2c855678c7fae8efbb3a7d3660c?apiKey=freekey

I'm gonna look into this problem and see how we can improve this experience.

**Comment by BifocalComb** [comment]
Great! Thanks so much for the prompt response.

**Comment by michaelScoff** [comment]
@BifocalComb I just checked on https://ethplorer.io/address/0xd26114cd6ee289accf82350c8d8487fedb8a0c07#pageSize=100, it sounds like they have 19hours delay for refreshing tokens, this is ridiculous. This is not acceptable! 

We need to find backend developers to make this easy to see your tokens! I'm gonna add this as a priority for us to work on! 

Are you developer? we might need some help to make experience better.

**Comment by michaelScoff** [comment]
I just realized that it's been around 18 hours since hard fork on Ethereum network, and their system wasn't updated to work properly. 

I will keep you updated on this issue.

**Comment by BifocalComb** [comment]
Oh I wish I were. I'm learning, but I'm afraid I'd be of no use to you.
What about the etherscan api?

**Comment by michaelScoff** [comment]
etherscan api does not provide public API for retrieving tokens yet 😢 but I will do more research

**Comment by BifocalComb** [comment]
https://etherscan.io/apis#tokens I might be misinterpreting this, but isn't
the bottom one token balance by address? I think you might have to pay for
more than 5 requests per second, though.

**Comment by michaelScoff** [comment]
This will return your balance if you know contract address in advance that you need to check. 

So let's say there is 1000 ERC20 contracts that you might have some amount on it, you would need to ask every contract how many tokens your wallet owns. 

`https://ethplorer.io` would give all the tokens that you address owns. I messaged their support for more info.

**Comment by BifocalComb** [comment]
Ah, ok. Thanks for the explanation! I'm glad I downloaded an app with such
a responsive dev team.

**Comment by michaelScoff** [comment]
@BifocalComb I'm going to close this issue in favor or https://github.com/TrustWallet/trust-wallet-ios/issues/56. 

Building this API will allow us to have all the transactions and tokens available for the users, and also ability to send token as a bonus. 

Hopefully to complete this in the next few weeks.

**Comment by michaelScoff** [comment]
@BifocalComb can you check your tokens in Trust now? they should be available to preview!

**Comment by michaelScoff** [comment]
@BifocalComb btw, I'm `OMG` hodler as well! Keep it up

**Comment by BifocalComb** [comment]
Cool! OMG certainly has potential. Unfortunately, I still am unable to see
token balances in the app.

**Comment by michaelScoff** [comment]
Can you double check your account? `0x24cc2359bc42b2c855678c7fae8efbb3a7d3660c` - it will say in Accounts page. 

I can see tokens now returned from their endpoint:
https://api.ethplorer.io/getAddressInfo/0x24cc2359bc42b2c855678c7fae8efbb3a7d3660c?apiKey=freekey

**Comment by BifocalComb** [comment]
Yea I just checked.. Ethplorer's API shows my correct balances... The app
still shows "No Tokens" when I try to see my tokens, and I only see my
transfer of 1.007 eth in the main account page.

**Comment by BifocalComb** [comment]
Sorry, I'm not sure I understand your question.. Do you mean what's worse:
showing the scientific notation value for balance or showing nothing?
Personally I'd rather see the scientific notation balance, just to confirm
my tokens were actually sent to the right address without having to use a
block explorer, but I could understand why that might confuse people. There
are 18 decimal places to the right of the ones place so I just imagine in
my mind that huge number divided by 10^18, and that's my balance.

**Comment by michaelScoff** [comment]
Never mind, I have fixed it, sending build to the App Store! It will take another day or two.

Demo:
![simulator screen shot - iphone se - 2017-10-17 at 13 16 00](https://user-images.githubusercontent.com/32179653/31687185-5f1e96c6-b33d-11e7-8fcc-125f513cb178.png)

**Comment by BifocalComb** [comment]
Great thanks! I'll definitely be recommending this app.. Best customer
service I've ever had by far. Some of my crypto-pals are devs so I'll
definitely lyk if I get any of them on the app.

Thanks again,
Andrew Grochan

**Comment by michaelScoff** [comment]
Yo! New version is out! I hope this should work now! 

![2017-10-18 16 15 55](https://user-images.githubusercontent.com/32179653/31747093-b71fd8c0-b41f-11e7-8b97-2a608e605f5f.jpg)

**Comment by BifocalComb** [comment]
Great! Just updated it. Thanks very much!
