### ISSUE TITLE
Create REST API for fetching transactions/tokens

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#56]
GET` /transactions/:wallet_address` (include all transactions for this address)
GET `/tokens/:wallet_address`
Support pagination for both of these API's

**Comment by maratsubkhankulov** [comment]
please detail motivation for creating REST API  as opposed to using infura/etherscan.

**Comment by michaelScoff** [comment]
Neither https://github.com/ethereum/wiki/wiki/JSON-RPC, or etherscan allows you to get list of transactions for specific address(for both transactions and internal transactions).

You can see thread on https://github.com/TrustWallet/trust-wallet-ios/issues/55 regarding `ethplorer.io` downtime! We should NOT let that experience to our customers.

Also this will give us ability to send tokens between accounts, it would generated unsigned transaction - to be be signed client-side by the user. Unless we device to make this client side. I still need to figure the best way to work with contracts on iOS side.

**Comment by michaelScoff** [comment]
Each transaction will have `action` - if it contains data. It will define what this specific transaction do, if we transfer tokens then it would look like this

```json
action: {
    "type": "token_transfer",
    "amount": "1", 
    "from": "0x....",
    "to": "0x....",
    "token": {
         "name": "Nice Token",
         "symbol": "NTK",
         "decimal": 18,
         "image": "https://....com/image/ntk.png",
         "totalSupply": "1312",
         "address" : "0x...."
    }
}
```

There is many actions that will be available in the future, like `deposit`, `add_owner`, `trade` and etc... 

This will allow us to clearly show to the user what this transaction do and show appropriate icon and information regarding this action.

**Comment by michaelScoff** [comment]
Here is an example for GET `tokens?address=0x...` endpoint:

```json
{
"address": "0x...",
"tokens": [{
    "address": "0xd26114cd6ee289accf82350c8d8487fedb8a0c07",
    "name": "OMGToken",
    "decimals": 18,
    "symbol": "OMG",
     "totalSupply": "140245398245132780789239631",
    "owner": "0x000000000000000000000000000000000000dead",
    "balance": 3412333140000000000,
}]
}
```
Example: https://api.ethplorer.io/getAddressInfo/0x24cc2359bc42b2c855678c7fae8efbb3a7d3660c?apiKey=freekey

**Comment by rip32700** [comment]
@michaelScoff  Do you need all those information about tokens in the response? Isn't it sufficient to only return address, symbol and balance of each token?

**Comment by michaelScoff** [comment]
@rip32700 `decimals` is required to calculate the correct balance, you can skip the rest for now

**Comment by michaelScoff** [comment]
Would be better to handle this client side instead, by asking balance from the list of tokens

**Comment by Sm00g15** [comment]
How can we monitor individual transactions to see if our users have sent over a specific amount of Eth or tokens?

**Comment by vikmeup** [comment]
@Sm00g15 ideally you want to use web3 and subscribe to the events and see all the transactions for specific address.

**Comment by Sm00g15** [comment]
sweeet do they have any hit limits that you're aware of? I don't see any indication that this is the case on their site

**Comment by vikmeup** [comment]
You should be fine with Infura.
