### ISSUE TITLE
Freezes when message to sign is too long, what is the limit?

### ISSUE THREAD

**Issue by 1blockologist** [TrustWallet/trust-wallet-ios#563]
Some of the examples here crash/freeze the Trust iOS app and I think this is primarily because of the length

https://danfinlay.github.io/js-eth-personal-sign-examples/

I like the idea of putting a terms of service into the signing prompt, but using the UIAlert on iOS doesn't seem to be best to handle this

**Comment by 1blockologist** [comment]
We are considering using long values for www.pareto.network, but are first checking the tooling of the signing mechanisms/wallets in the Ethereum ecosystem

**Comment by vikmeup** [comment]
Yes, I will double check on this. 

What’s the use case for long values?

**Comment by 1blockologist** [comment]
The use case is to put our terms of service as the message to sign

**Comment by vikmeup** [comment]
@1blockologist should be fixed on `master` now, are you able to pull it? Otherwise, it will go out in the next App Store release, either on Friday or early next week.
