### ISSUE TITLE
Cannot import address by key file and password

### ISSUE THREAD

**Issue by jmenhome** [TrustWallet/trust-wallet-ios#573]
Hello!
I try to import exists account to my trust wallet app. JSON file:

Screenshot of error: 
![photo_2018-04-04_13-53-21](https://user-images.githubusercontent.com/16046665/38303978-6c14647a-3810-11e8-8185-39d88634a9ae.jpg)

On Android version all works fine.

**Comment by vikmeup** [comment]
@jmenhome hey, I removed your keystore, so it won't be exposed to the users. 

Where did you create this keystore? can you send me only the part with PBKDF2 parameters in that keystore JSON file?

I bet it's related to some of the parameters for decryption that might not be supported by Trust iOS app.

**Comment by jmenhome** [comment]
I see this issue on few accounts created by geth console (personal.newAccount()), all of them have no password (empty password). I create new clear one specially to show this issue, so we can publish this key file without risk.
Sorry, but I don't know which part is PBKDF2, maybe I can publish full key file?

**Comment by jmenhome** [comment]
"kdf":"scrypt",
		"kdfparams":{
			"dklen":32,
			"n":262144,
			"p":1,
			"r":8,
			"salt":"495fab1393fdb410cdafaf6d697c86c7fb354984512cc6860feacbba56c02e09"
		},

**Comment by vikmeup** [comment]
@alejandro-isaza can you take a look at this? You might have more insight 

@jmenhome can you provide full Keystore for debugging? Is there is not risk

**Comment by alejandro-isaza** [comment]
This is the fix: https://github.com/krzyzanowskim/CryptoSwift/pull/602

**Comment by vikmeup** [comment]
@alejandro-isaza CryptoSwift merged request. Can you pull latest to close this issue? Thanks

**Comment by alejandro-isaza** [comment]
Still no release though, we would have to point to master

**Comment by vikmeup** [comment]
@jmenhome this is fixed on the master now!
