### ISSUE TITLE
Payments go 2 times

### ISSUE THREAD

**Issue by jRazer** [TrustWallet/trust-wallet-ios#577]
On try send coins - first pic and nothing happens
Next try - send, and send previous coins - as on second pic
![pic-1](https://user-images.githubusercontent.com/2252869/38379017-1603fb88-3908-11e8-85ca-8acc85aed1e7.jpg)
![pic2](https://user-images.githubusercontent.com/2252869/38379021-1ceb1abc-3908-11e8-925b-eeb7588a52e6.png)
![img-20180405-wa0005](https://user-images.githubusercontent.com/2252869/38379896-d1bcd690-390a-11e8-8a9e-a4a65cdf7b41.jpg)

**Comment by vikmeup** [comment]
Hey! This is an issue on Ethereum Classic node. Their team can’t even provide stable node for the users to use. I’m gonna dig into this
