### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by heiterwelt** [TrustWallet/trust-wallet-ios#582]
Unexpected platform condition (expected 'os', 'arch', or 'swift')

**Comment by MillerApps** [comment]
@heiterwelt can you provide more details? What version of Xcode are you using? Did you install all the dependencies? Where is the error output? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MillerApps** [comment]
@heiterwelt did you resolve this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
@MillerApps We don’t have such problem. Make sure you are on Xcode 9.3 and run make bootstrap

**Comment by heiterwelt** [comment]
ok, let me try, my Xcode version is 9.1

**Comment by heiterwelt** [comment]
ok, let me try, my Xcode version is 9.1

**Comment by MillerApps** [comment]
@heiterwelt please update to the latest Xcode release (9.3).
