### ISSUE TITLE
Split collectibles into categories

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#584]
I'm getting more collectibles now, it's hard to manage them, it would be great to split those into categories, rather than one list.

**Comment by kolya182** [comment]
@vikmeup Are they not categorized on client ?. I improved assets fetching speed, do you still want this API ?.
![img_3281](https://user-images.githubusercontent.com/3277207/39158851-2d41263c-4717-11e8-90a0-6b302e850ba9.PNG)

**Comment by vikmeup** [comment]
@kolya182 I have over 30 different items now, I bet it will grow eventually. that case we should add support to 

1) get a list of categories that I own some collectables
2) get items for specific category that I own
