### ISSUE TITLE
Deep Links

### ISSUE THREAD

**Issue by dangell7** [TrustWallet/trust-wallet-ios#630]
Is there any plan to support deep links? I.e. so that native iOS applications could call a deep link to the wallet and create a transaction/prompt the user to accept the transaction. I think could be a big problem solver for native iOS applications that want to support etherum but do not want to create their own wallet or create an account for their users.

**Comment by vikmeup** [comment]
Yes! We plan to add support next week. 

Can you message me on telegram: vikmeup?

**Comment by vikmeup** [comment]
Closing this for now! Just implemented basic logic for open specific URL.
