### ISSUE TITLE
Invalid Sender Error on sending ETH

### ISSUE THREAD

**Issue by jRazer** [TrustWallet/trust-wallet-ios#640]
Invalid Sender Error on sending Ethereum

**Comment by vikmeup** [comment]
@jRazer I assume you are on iOS 10 right?

This is fixed on master and will be available on the App Store in the next few days.

**Comment by jRazer** [comment]
Tell me how long to wait for the update

**Comment by MillerApps** [comment]
It all up to Apple at this point. You can join the [beta](https://trust-wallet-beta.herokuapp.com/) if you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
