### ISSUE TITLE
Implement QR code parser

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#65]
https://github.com/TrustWallet/trust-wallet-ios/blob/master/Trust/Transfer/Controllers/SendViewController.swift#L137 

Ref: https://github.com/ethereum/EIPs/issues/67

**Comment by KamuelaFranco** [comment]
Was this implemented?

**Comment by michaelScoff** [comment]
It is! We have ability to parse both formats: ethereum:, omg:, or just hex address
There is an issue though to refactor: https://github.com/TrustWallet/trust-wallet-ios/issues/92. Would you like to take a look?

**Comment by KamuelaFranco** [comment]
Does this mean that something like `ethereum:0xiAmAnAddress?value=5000?data=0x324af3afdf` is actually working? I'm using a QR code generator right now to test with Trust Wallet, and I'm not seeing anything beyond something like `ethereum:address` being parsed. Is that correct?

**Comment by michaelScoff** [comment]
We only parse ethereum address. Most of the services only have hex value for the QR image

But for the future use it would be great to have EIP67 implemented, but not many services conform to it yet

**Comment by KamuelaFranco** [comment]
Thank you for this update. I was considering restricting support for wallets that support the burgeoning protocol, even if not completely standard. But it seems that no wallet supports the data/bytecode portion of the address, which is crucially needed for my application.

**Comment by michaelScoff** [comment]
What’s your application? Message me on telegram: vikmeup. I would love to help if I can
