### ISSUE TITLE
Import Wallet View text change

### ISSUE THREAD

**Issue by slgraham** [TrustWallet/trust-wallet-ios#651]
ImportWalletViewController.swift line 92

Current text is "Importing wallet as easy as creating", but should be more like...

1. "Importing is just as easy as creating"
2. "Importing a wallet is as easy as creating one"

Number 1 is probably the better option so it stays on a single line

Also, this text is not localizable since it's class is NSAttributedString, not NSLocalizedString.

**Comment by MillerApps** [comment]
Feel free to create a PR with a fix. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
@slgraham do you have any thoughts on this? do we even need to have any copy on import screen next to that image?
