### ISSUE TITLE
Remove EAIntroView dependency

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-wallet-ios#66]
`EAIntroView` sucks at customization, build own own implementation that has scroll view and action buttons.

**Comment by troydo42** [comment]
Do you a mockup/design for how this would potentially look like ?

**Comment by michaelScoff** [comment]
Hey, @troydo42 I would like to make same as it as right now (but I will tweak little later) but, `EAIntroView` make it hard to move labels up and down. 

- buttons should always alignted to the bottom
- ImageView - <=40px space - titleLabel <=40px space -descriptionLabel <=40px space 

Please join Slack: https://join.slack.com/t/trust-wallet/shared_invite/enQtMjc1NDIzNTc1NzgxLTg1M2U5N2MzNmVlOTBhYTM4NDMwZDM2OTg1ZDA4NmU2OWFiNTZlN2Q4YmNmZGViYTE5ZTAyM2I3YTZlNjYxYjE, we can chat :) I would really appreciate your help! 

Current state:
![simulator screen shot - iphone x - 2017-11-20 at 11 41 04](https://user-images.githubusercontent.com/32179653/33037896-bb8fde50-cde7-11e7-9ece-2c8fd0edb8c8.png)

**Comment by michaelScoff** [comment]
@troydo42 I would like to have same spacing I mentioned for iPad as well, so it's consistent across all devices

![simulator screen shot - ipad air 2 - 2017-11-20 at 11 46 58](https://user-images.githubusercontent.com/32179653/33038138-8ca1132e-cde8-11e7-99a9-ff680f6f4545.png)

**Comment by michaelScoff** [comment]
It looks ever worst in some cases

![simulator screen shot - ipad pro 9 7 inch - 2017-11-26 at 21 12 50](https://user-images.githubusercontent.com/32179653/33251833-a89db022-d2ee-11e7-83c0-290eb4f81583.png)
