### ISSUE TITLE
App not supported on iOS 9

### ISSUE THREAD

**Issue by D3V4N5H** [TrustWallet/trust-wallet-ios#668]
iPhone 4s doesn't get updates later than iOS 9.3.5 so I'm not able to install the app.

**Comment by vikmeup** [comment]
Oh, you have very old version! 

You might need to upgrade the phone!

**Comment by MillerApps** [comment]
@D3V4N5H supporting iOS 9 would not be worth it considering only around 7% of devices are below iOS 10. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
In order to keep technology moving need to ditch support for old phones.
