### ISSUE TITLE
Idea - consider a back button to the browser

### ISSUE THREAD

**Issue by davecraige** [TrustWallet/trust-wallet-ios#669]
I believe the iOS DApp browser might want to have a back button when a customer is within an DApp.  I believe that over 95% of customers don't realize you can swipe the screen to go back.  (I even forgot that as well)

![screen_shot_2018-04-20_at_1 38 31_am](https://user-images.githubusercontent.com/2782676/39157012-f9f7d894-4715-11e8-9c81-b14499b7af96.png)
_Here is how Apple designed it for Safari.  Note the small back button in the bottom left_

**Comment by MillerApps** [comment]
Already implemented. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davecraige** [comment]
Oh sweet.  Thanks guys!
