### ISSUE TITLE
Can't send ETH and ETC

### ISSUE THREAD

**Issue by Chxos** [TrustWallet/trust-wallet-ios#676]
Every time I try to send ETC/ETH to my Binance account I get "invalid sender" error, I tried putting a high gas limit and same thing, doesn't work, please help guys.

**Comment by MillerApps** [comment]
I assume you are on iOS 10. It has been fixed, just waiting for Apple to approve the build. If at all possible update to iOS 11. One last alternative is to join our [beta](https://trust-wallet-beta.herokuapp.com/). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Chxos** [comment]
So if i update to iOS 11 i'll be able to send right away? thanks for the help btw.

**Comment by MillerApps** [comment]
Yes, it should work on iOS 11. You are welcome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Chxos** [comment]
Thanks man i'll try right now.

**Comment by MillerApps** [comment]
Okay, let us know how it goes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vikmeup** [comment]
@Chxos also another solution to use beta build: https://trustwalletapp.com/beta.
