### ISSUE TITLE
Error when make bootstrap

### ISSUE THREAD

**Issue by Ankarrr** [TrustWallet/trust-wallet-ios#680]
Installing TrezorCrypto (0.0.5)
[!] /bin/bash -c
set -e
git submodule update --init
sed -i '' -e 's:ed25519-donna/::g' ./**/*.c
sed -i '' -e 's:ed25519-donna/::g' ./**/*.h
sed -i '' -e 's:USE_ETHEREUM 0:USE_ETHEREUM 1:g' trezor-crypto/options.h

sed: can't read : No such file or directory

**Comment by vikmeup** [comment]
Make sure you run latest Xcode and cocoa pods
