### ISSUE TITLE
Export file(wallet) naming  

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-ios#70]
1. Give export file user-friendly name. Instead of  "Text File.txt" something like "0x1234556.... 26.10.2017.txt" whre 26.10.2017 - export time or creating time on your choice. 
2. Add ability to rename the export file.
 Use case: If I have more than one wallet and want to export them in the same folder.

**Comment by michaelScoff** [comment]
We could possible name generic naming for them: `wallet-0x123.json` or so

**Comment by michaelScoff** [comment]
It's a tricky problem, in order set filename, we need to save keystore in term folder with desired name and then export that URL. 
Ref: https://thomasguenzel.com/blog/2015/04/16/uiactivityviewcontroller-nsdata-with-filename/

I have concert regarding storing locally, but we could probably delete once keystore stored.
