### ISSUE TITLE
can't get trust wallet ios app in China, really need it

### ISSUE THREAD

**Issue by huahuayu** [TrustWallet/trust-wallet-ios#703]
Hi do you have a plan to get into China apple store, I can't find it in China apple store, I can only use an us apple store account to download it.

we develop Dapps and I find trust wallet is the best among Dapp browser, really need it for our mobile users.

**Comment by vikmeup** [comment]
I will check with Apple team on this, when we first submitted in November it wasn’t allowed.

**Comment by hewigovens** [comment]
@huahuayu no only Trust, you can't download other wallets apps too. Thanks to the regulation.

**Comment by vikmeup** [comment]
Should be available now

**Comment by vikmeup** [comment]
@huahuayu can you access by https://itunes.apple.com/us/app/trust-ethereum-wallet/id1288339409?mt=8 ?

**Comment by huahuayu** [comment]
@vikmeup, as you can see the link itself, is with "us" inside, not "china" or "cn", we tried, this item is not available in China. Please reopen this issue.
![image](https://user-images.githubusercontent.com/1725060/39957990-94a309aa-562e-11e8-804b-ecb0248b3af2.png)

**Comment by vikmeup** [comment]
It’s not up to us, Apple doesn’t allow trust to be on china App Store

**Comment by MillerApps** [comment]
@huahuayu You can clone the repo and install on your device through Xcode.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kishanjvaghela** [comment]
@vikmeup You can use enterprise version for ios https://itunesconnect.apple.com.

Just like binance did for iPhone. https://www.binance.com/ios-beta.html

Anyone can download after that in china without AppStore.
