### ISSUE TITLE
QR scan to open dapp / browser link

### ISSUE THREAD

**Issue by NukeManDan** [TrustWallet/trust-wallet-ios#719]
Here: https://github.com/TrustWallet/trust-wallet-android-source/issues/17

From the top right dropdown menu on the dapp browser page - "QR Code scan"

I get a comara portal, and the app seems to capture a QR - as it terminates the camera video, but then nothing happens. 

eg - this should go to https://google.com :

![qrcode 44851460](https://user-images.githubusercontent.com/35669742/39962906-366a3ee4-561a-11e8-8261-6dc8d843b58e.png)

**Comment by vikmeup** [comment]
@NukeManDan take a look at this article to enable deep linking https://medium.com/p/6a4712b9b9a4/edit
