### ISSUE TITLE
Contacts list

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-ios#73]
Allow user to send/request against addresses pulled from a contact list. Text entry or QR codes are okay, better if they can be stored against contacts and allow use of friendly wallet names after that.

**Comment by michaelScoff** [comment]
How would you approach this problem if you didn't have backend? 

At this point I don't feel like storing any contracts servers side, wonder if there is solution for it? I would not want to give up on privacy but at the same time keep convenience for using the app

**Comment by Narragansett** [comment]
No backend involvement. Contacts list on the phone. Saves user from having to manage wallet addresses in their head. Financial and messaging apps typically do tap into the phone contacts list with user permission to initiate payments. I suppose the user could maintain a separate notes app with friendly names against wallet addresses. Rather than send money by entering the wallet address would be easier to just enter a contact or friendly name from a phone contact list or separate notes section of the app.
