### ISSUE TITLE
App colors for icon, splash page

### ISSUE THREAD

**Issue by Narragansett** [TrustWallet/trust-wallet-ios#74]
Blue on white icon and splash page looks stark. Trust-wallet-android has a better icon style if you could use it. Splash page blue on white looks too plain, if you reverse the colors it will look boss.

**Comment by michaelScoff** [comment]
Simplicity is the key here. I had to make design for android to reverse color(to follow material design patterns)

For now I would like to keep product as simple as possible, it's easier for vision perception.

**Comment by Narragansett** [comment]
Good reasoning. You manage things well and that helps!
Thank you,
Jerry
