### ISSUE TITLE
Support for Ellaism network?

### ISSUE THREAD

**Issue by stevemulligan** [TrustWallet/trust-wallet-ios#740]
Hi, I'm wondering if it would be possible to add support for the Ellaism network to TrustWallet.

Ellaism is an Ethereum-like network with no premine and no dev fees.  https://ellaism.org

I have changes in a fork that are working ok so far.  I have a question about `remoteURL` in Trust/Settings/Types/RPCServers.swift, line 110.  What value would go in there?

**Comment by vikmeup** [comment]
How many users do you guys on the network? 
How many dapps do you guys have, is that your purpose for the nerwork? 

Can you telegram: @vikmeup? I’m always happy to add as long as it gives value to the users.

**Comment by vikmeup** [comment]
Closing this for now, until Ellaism has enough community that this will be needed!

**Comment by vikmeup** [comment]
https://github.com/ellaism/trust-wallet-ios/issues/9#issuecomment-404325381
