### ISSUE TITLE
Rinkeby and OpenSea.io

### ISSUE THREAD

**Issue by abcoathup** [TrustWallet/trust-wallet-ios#747]
When using Rinkeby network and viewing an individual collectible (ERC721) and pressing Open on OpenSea.io this opens https://opensea.io/assets/[contract]/[tokenID] when it should open https://rinkeby.opensea.io/assets/[contract]/[tokenID]

Not sure if this should be fixed on the trust side or opensea.

**Comment by OlegGordiichuk** [comment]
@abcoathup thx for the request. It should be done in the Trust side. Working on it.
