### ISSUE TITLE
iOS 12 preparation.

### ISSUE THREAD

**Issue by OlegGordiichuk** [TrustWallet/trust-wallet-ios#748]

**Comment by MillerApps** [comment]
I tested on iOS 12. Noticed two notable issues. 
- When using a passcode and Touch ID, the keypad stays on screen. 
- The DApp browser doesn’t appear to work anymore. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OlegGordiichuk** [comment]
Currently working on it.

**Comment by vikmeup** [comment]
@OlegGordiichuk let's make changes to make sure we are ahead of time on supporting iOS 12.
