### ISSUE TITLE
The wrong block is shown in token transactions details. Change to correct after confirmations. 

### ISSUE THREAD

**Issue by kolya182** [TrustWallet/trust-wallet-ios#76]
@michaelScoff Is this normal behave ?.
![img_2620](https://user-images.githubusercontent.com/3277207/32701970-1472ec2e-c794-11e7-864b-bd21bf5d3098.PNG)
![img_2621](https://user-images.githubusercontent.com/3277207/32701975-1653632a-c794-11e7-945c-e613d3d09982.PNG)
Change to correct after some confirmations:
![img_d1be202a4b9b-1](https://user-images.githubusercontent.com/3277207/32701988-6c9d3b34-c794-11e7-9a79-8f478f5eadfa.jpeg)

**Comment by michaelScoff** [comment]
@kolya182 it's not expected value, etherscan started giving transactions foe pending blocks as well in the past two weeks, kinda strange. Added check to show 0 confirmations instead

This issue should be resolved once we have our backend integrated for transactions
