### ISSUE TITLE
The EOS chain has been launched. Does Trust plan to support it?

### ISSUE THREAD

**Issue by cppfuns** [TrustWallet/trust-wallet-ios#774]

**Comment by vikmeup** [comment]
@cppfuns Trust will have support for EOS within few months! Preparing infrastructure for it

**Comment by cppfuns** [comment]
There is an urgent need for a similar trust-web3-provider, perhaps called trust-eosjs-provider. If it is ready, we hope to see it as soon as possible. We have been paying attention to trust, thanks to trust's dedication.

**Comment by vikmeup** [comment]
@cppfuns I think first step would be to add support for the EOS coin/network itself to the Trust and then add support for dapp browser! This might take some time, but I would recommend doing `trust-eosjs-provider` yourself, this way you can build faster and we can reuse on Trust side later on.

**Comment by vikmeup** [comment]
Moving everything into this: https://github.com/TrustWallet/trust-wallet-ios/issues/803
