### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by BloodyPixy** [TrustWallet/trust-wallet-ios#776]
There is an issue now. Travis CI fails on one test and it has affected https://github.com/TrustWallet/trust-wallet-ios/pull/775, https://github.com/TrustWallet/trust-wallet-ios/pull/772, https://github.com/TrustWallet/trust-wallet-ios/pull/771.  I have localized the problem.

<img width="919" alt="screen shot 2018-06-26 at 22 57 57" src="https://user-images.githubusercontent.com/11520923/41936038-7f86bbaa-7994-11e8-8be4-6c05b66e45ce.png">
<img width="761" alt="screen shot 2018-06-26 at 22 55 33" src="https://user-images.githubusercontent.com/11520923/41936036-7f41824c-7994-11e8-93b8-49b23d577377.png">
<img width="761" alt="screen shot 2018-06-26 at 22 56 28" src="https://user-images.githubusercontent.com/11520923/41936037-7f6493fe-7994-11e8-819d-248baebaf694.png">

**Comment by BloodyPixy** [comment]
<img width="695" alt="screen shot 2018-06-26 at 23 40 39" src="https://user-images.githubusercontent.com/11520923/41937969-6a3a8e4c-799a-11e8-9ca9-f8bd99b9954d.png">
<img width="778" alt="screen shot 2018-06-26 at 23 41 00" src="https://user-images.githubusercontent.com/11520923/41937970-6a55592a-799a-11e8-999b-2fdceaa87cb6.png">

**Comment by BloodyPixy** [comment]
<img width="778" alt="screen shot 2018-06-26 at 23 41 00" src="https://user-images.githubusercontent.com/11520923/41939179-ad57ad74-799d-11e8-9850-d411b87a6c83.png">
<img width="695" alt="screen shot 2018-06-26 at 23 40 39" src="https://user-images.githubusercontent.com/11520923/41939186-b04cd09a-799d-11e8-9e06-22a870b8b25e.png">

The code in the test is synchronous. 

The code in the createInstantWallet is asynchronous. 

By the time `coordinator.navigationController.viewControllers[0]` is called, there aren't any controllers, even root, as the `FakeNavigationController` doesn't have any root controller. I believe, this is why the test fails.

**Comment by BloodyPixy** [comment]
I can suggest changing `coordinator.start(.createInstantWallet)` to `coordinator.pushBackup(for: .make())`. This should fix the issue and nothing will change from result perspective, as we do the same thing in our `createAccount` method for `FakeEtherKeystore`. @OlegGordiichuk what do you think?

**Comment by vikmeup** [comment]
@BloodyPixy Looks good, just added test for push backup: https://github.com/TrustWallet/trust-wallet-ios/commit/84a382f9d5c9615fda3abd42957ccb3bfc96b3d7
