### ISSUE TITLE
Tokens price is not displayed

### ISSUE THREAD

**Issue by BloodyPixy** [TrustWallet/trust-wallet-ios#778]
Realm stores lowercased contract address for some reason.

In my case, the TNT token value in selected currency was not displayed. I believe it affects all of the tokens. Upon investigation, I found out that TockenTicker will always be nil for TNT. It is because when trying to compare `"TNT_0x08f5a9235B08173b7569F83645d2c7fB55e8cCD8_tickers-USD-1" `and `"TNT_0x08f5a9235b08173b7569f83645d2c7fb55e8ccd8_tickers-USD-1"` it fails, as one of them is completely lowercased.

![img_9925](https://user-images.githubusercontent.com/11520923/41957652-4e27adce-79f0-11e8-970e-52e24eb9cb88.PNG)
<img width="424" alt="screen shot 2018-06-27 at 09 37 19" src="https://user-images.githubusercontent.com/11520923/41957556-049c0ad8-79f0-11e8-8909-812ab9017373.png">
<img width="504" alt="screen shot 2018-06-27 at 09 40 36" src="https://user-images.githubusercontent.com/11520923/41957557-05c6f238-79f0-11e8-8b11-367d75165280.png">
<img width="768" alt="screen shot 2018-06-27 at 09 42 22" src="https://user-images.githubusercontent.com/11520923/41957558-06944422-79f0-11e8-9967-ab8cf4611973.png">
<img width="231" alt="screen shot 2018-06-27 at 09 44 39" src="https://user-images.githubusercontent.com/11520923/41957561-079c8b18-79f0-11e8-8e54-8418dfc1ac3a.png">

As you can see here, Reals objects have contract lowercased for TNT. I think this is expected, because when copying contract address from etherscan f.e., the value is lowercased.

<img width="976" alt="screen shot 2018-06-27 at 09 58 46" src="https://user-images.githubusercontent.com/11520923/41957829-e78ce40c-79f0-11e8-9004-4fb1867346f9.png">

I think we should create a fallback. The address will be unique in both cases. So we will try to filter by address as is if nil, try to filter by lowercased.

**Comment by vikmeup** [comment]
@BloodyPixy I think the issue here, why it is being stored here in the first place? We need to always store values in the checksum version. in that case `Address` model

**Comment by BloodyPixy** [comment]
@vikmeup , you mean `eip55String`? Yeah, that's what I thought when I saw the code. But as far as I see, this is not how it's done in our case.  
Should we add `Address` property to our `CoinTicker` and use its `eip55String` function for storing in Realm and comparing?  
I will work on that if needed, for now I have created a PR for a fallback to lowercase, if you could check it, that'd be great.

**Comment by BloodyPixy** [comment]
Fix applied https://github.com/TrustWallet/trust-wallet-ios/commit/e36394b1be75fba77646f26401bbf1ddf0d4ab06.
