### ISSUE TITLE
The outcome amount formatting 

### ISSUE THREAD

**Issue by VNadygin** [TrustWallet/trust-wallet-ios#78]
Was trying to send 0.0005 and it's formated as 0.000
![image 2017-11-13 21 55 55](https://user-images.githubusercontent.com/12998927/32743433-6d2031c2-c8bd-11e7-9cfb-159e4b5c0269.jpg)

**Comment by kolya182** [comment]
@VNadygin Just want to clarify, you were trying to send 0.0005 tokens, not ETH, correct ?.

**Comment by VNadygin** [comment]
@kolya182 No. It's ETH. Maybe we should check the value and if the value if less than 0.001 add < symbol.

**Comment by michaelScoff** [comment]
@aleph7 how hard would it be to add this feature to `EtherNumberFormatter`? this is not a priority at all, mostly curious about overall UX for representing small amounts

so if the amount is `0.0000001`, we say `<0.0000`, kinda weird though. Any thought on this?  what're other ways to display very small amount?

**Comment by aleph7** [comment]
We should switch to using pwei, twei, and so on as necessary. So 0.001 would be `1 pwei`, 0.000001 would be `1 twei` and so on.

**Comment by michaelScoff** [comment]
@aleph7 this might work for developers, but most of our users are noobs :( this would be really confusing for them.
