### ISSUE TITLE
how trust call a smart contract

### ISSUE THREAD

**Issue by steve7688** [TrustWallet/trust-wallet-ios#785]
how trust call a smart contract

**Comment by steve7688** [comment]
@vikmeup you mean this function in class TokensBalanceService.swift?

    func getEthBalance(
        for address: Address,
        completion: @escaping (Result<Balance, AnyError>) -> Void
    ) {
        let request = EtherServiceRequest(batch: BatchFactory().create(BalanceRequest(address: address.description)))
        Session.send(request) { result in
            switch result {
            case .success(let balance):
                completion(.success(balance))
            case .failure(let error):
                completion(.failure(AnyError(error)))
            }
        }
    }

**Comment by vikmeup** [comment]
@steve7688 This is ETH balance, take a look at the token balance. I’m on the phone atm, but I can show tmw if you won’t find it

**Comment by steve7688** [comment]
@vikmeup thank you for the help.I'm new to Ethereum.

you mean the operation [Add Custom Token] in Trust APP?

**Comment by steve7688** [comment]
@vikmeup Hello vikmeup.Could you show me some code?Thank you very much.

**Comment by steve7688** [comment]
Did trust call a smart contract by web3.js?Through a hidden wkwebview?

**Comment by vikmeup** [comment]
@steve7688 https://github.com/TrustWallet/trust-wallet-ios/blob/9c95933b25d4c60661735d8cec4bd4713d011f28/Trust/Tokens/Coordinators/TokensBalanceService.swift#L12 that's how we call `balanceOf` on the smart contract

no! we do not use JS to call smart contract, unless it's a web3 provider for the dapp browser

**Comment by steve7688** [comment]
@vikmeup 

```
enum TransferType {
    case ether(destination: Address?)
    case token(TokenObject)
    case nft(NonFungibleTokenObject)
    case dapp(DAppRequester)
}
```
Could you tell me What every element in this enum means?And their function?When they will be used?

**Comment by AngryBaby** [comment]
support erc20 extension function for approveAndCall?
i found ERC20Encoder have no encode this function, how to support approveAndCall?

**Comment by AngryBaby** [comment]
i found the class ERC20Encoder unsupport erc20 extension function approveAndCall, how to support this function?
