### ISSUE TITLE
Unable to register new wallet without relaunching application

### ISSUE THREAD

**Issue by BloodyPixy** [TrustWallet/trust-wallet-ios#788]
When trying to create new wallet on iPhone 5s, '`Done`' button does nothing (see screenshot).

![1](https://user-images.githubusercontent.com/11520923/42087580-44930398-7b9f-11e8-92dd-ea2b3cd3da15.png)

In `WalletCoordinator`, `delegate?.didCancel(in: WalletCoordinator)` is called on '`Done`' button click. After that the coordinator is removed and the user in not navigated anywhere. 

I think that the wrong delegate method is executed. 
On that stage we have an `Account` object, but I'm not aware how to get `Wallet` object from it in order to call `delegate?.didFinish(with: Wallet, in: WalletCoordinator)` and not to alter existing logic. @vikmeup could you suggest something?

**Comment by vikmeup** [comment]
@BloodyPixy I will take a look at this now.
