### ISSUE TITLE
navigator.language always returns 'en'

### ISSUE THREAD

**Issue by excaliburcoin** [TrustWallet/trust-wallet-ios#790]
In dApp Browser on Trust Wallet, navigator.language always returns 'en' regardless of device setting.
This behavior breaks i18n support of dApps.

CFBundleAllowMixedLocalizations would resolve this problem.
https://stackoverflow.com/questions/3856158/uiwebview-localization/3896330#3896330

**Comment by dotneet** [comment]
Thanks!

**Comment by excaliburcoin** [comment]
Thanks!
