### ISSUE TITLE
App no lunger usable after switching from Mainnet to Kovan

### ISSUE THREAD

**Issue by kytzu** [TrustWallet/trust-wallet-ios#791]
I used the app for long time, having 5 accounts imported (Ethereum mainnet). Trying for the first time to switch to Kovan, app get frozen and no longer starts. After restart, it only shows the launch screen for a few seconds and then crashes.

Using iPhone 7+ with iOS 11.4. It also happened on another device using the same steps.

Regards,
Calin

**Comment by vikmeup** [comment]
@kytzu can you try latest master? it should work now, I believe it's fixed
