### ISSUE TITLE
Failed to load 'TrustWalletSDK' podspec: 

### ISSUE THREAD

**Issue by W-B-S** [TrustWallet/trust-wallet-ios#810]
CocoaPods 1.5.3 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.3

Analyzing dependencies
[!] The version of CocoaPods used to generate the lockfile (1.5.3) is higher than the version of the current executable (1.3.1). Incompatibility issues may arise.
Pre-downloading: `JSONRPCKit` from `https://github.com/bricklife/JSONRPCKit.git`, commit `50d19a4f7ec593ac5e07cffa1e11c17f1fbe347d`
Pre-downloading: `QRCodeReaderViewController` from `https://github.com/yannickl/QRCodeReaderViewController.git`, commit `80bd79cbeede842949b229f81bc6328f53701c5a`
Pre-downloading: `TrustKeystore` from `https://github.com/TrustWallet/trust-keystore`, commit `9efdccfcace4d42874838243cb2b4710636fd563`
Pre-downloading: `TrustWalletSDK` from `https://github.com/TrustWallet/TrustSDK-iOS`, commit `82c06558df5e6a75bd9c195a4e76536618e76a9a`
[!] Failed to load 'TrustWalletSDK' podspec: 
[!] Invalid `TrustSDK.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="TrustSDK">.

 #  from /var/folders/0j/8lghc3kd7yx2c_1lp9zhc6_h0000gn/T/d20180707-13623-vkdkm8/TrustSDK.podspec:9
 #  -------------------------------------------
 #    s.ios.deployment_target = '10.0'
 >    s.swift_version = '4.0'
 #  
 #  -------------------------------------------

make: *** [install] Error 1
ACA81E24:trust-wallet-ios wsli$

**Comment by vikmeup** [comment]
Make sure to run latest Xcode version
