### ISSUE TITLE
Speed up launch time

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#812]
Info: https://useyourloaf.com/blog/slow-app-startup-times/

**Comment by OlegGordiichuk** [comment]
Current statistics:

Total pre-main time: 722.04 milliseconds (100.0%)
         dylib loading time: 192.04 milliseconds (26.5%)
        rebase/binding time: 375.07 milliseconds (51.9%)
            ObjC setup time:  80.15 milliseconds (11.1%)
           initializer time:  74.63 milliseconds (10.3%)
           slowest intializers :
               libSystem.dylib :   2.92 milliseconds (0.4%)
    libMainThreadChecker.dylib :  15.59 milliseconds (2.1%)
                         Trust :  46.08 milliseconds (6.3%)

**Comment by vikmeup** [comment]
@OlegGordiichuk nice work on improving this!
