### ISSUE TITLE
I have sent three transactions in the last week and they are still Pending

### ISSUE THREAD

**Issue by Diamonium** [TrustWallet/trust-wallet-ios#816]
Hi, I have sent three transactions in the last week and they are still Pending in the TRUST WALLET as they are still unconfirmed.

My Balance of ETH has not changed and I would like to cancel these 3 transactions as I paid the amounts through my blockchain.info wallet that went through straight away. 

What is the problem with the TRUST WALLET as it seems that I cannot trust it to send ETH anymore?

**Comment by vikmeup** [comment]
Ethereum network is clogged, it’s not relayed to the wallet! 

Use higher gas fee to send transaction. 

Take a look here: https://help.trustwalletapp.com/hc/en-us/articles/360004080194-Pending-Stuck-transactions
