### ISSUE TITLE
[UI] Remove extra plus sign on collectibles view

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-wallet-ios#820]
Plus sign should be removed for collectibles view

iPad iOS 10.3

![simulator screen shot - ipad air - 2018-07-09 at 03 45 45](https://user-images.githubusercontent.com/1641795/42446294-95dedc62-832a-11e8-9295-6d32635e7f90.png)

**Comment by OlegGordiichuk** [comment]
We should apply this only for iOS 10.3. I will take a look of the possible ways.

**Comment by vikmeup** [comment]
@OlegGordiichuk if it's only iOS 10.3 let's close this issue then. 

All users are on iOS 11 :)
