### ISSUE TITLE
Support current merged EIP-712 specification

### ISSUE THREAD

**Issue by leroldary** [TrustWallet/trust-wallet-ios#825]
ethereum/EIPs#712 is merged. When/How do you plan to update from your current implementation of
eth_signTypedData to the new one specified in EIP-712?

**Comment by vikmeup** [comment]
@hewigovens can you take a look to see what we need to finish?

**Comment by leroldary** [comment]
Metamask will add a deprecation warning to the old implementation in the next release https://github.com/MetaMask/metamask-extension/pull/4905 and in the next release thereafter replace it with the current new EIP712 specification https://github.com/MetaMask/metamask-extension/pull/4803.

Would be great if you could update your implementation to remain compatible with metamask.

**Comment by hewigovens** [comment]
Thanks for your information, we will work on this soon

**Comment by leroldary** [comment]
Just noticed,  trust wallet for android has an EIP-712 implementation. But it seems it's neither compatible with the new merged EIP-712 specification nor with the old one implemented in MetaMask (which will be replaced soon). Which version of the specification is currently implemented for the android version?

**Comment by hewigovens** [comment]
@leroldary Thanks, we have a [branch](https://github.com/TrustWallet/trust-wallet-ios/tree/issues/825) if you'd like to track the progress.
