### ISSUE TITLE
Push notifications aren't received when switching networks

### ISSUE THREAD

**Issue by maratsubkhankulov** [TrustWallet/trust-wallet-ios#829]
Steps to reproduce:
1. Select ethereum network and your favorite wallet in settings
2. Switch network to Ropsten
3. Observe that push notifications are still turned on in settings
4. Send a small about of Ropsten Ether to the same wallet
5. Send app to background
6. Wait a while...
7. Observe that the is no notification

Success case:
1. After the previous steps...
2. Unselect and select push notifications again
3. Send a small amount
4. Send app to background
5. Observe that a push notification is sent

**Comment by vikmeup** [comment]
We gonna be observing all the networks now, it will fix this.
