### ISSUE TITLE
QR-code scanning: TrustWallet uses `wei`, most wallets use `eth`

### ISSUE THREAD

**Issue by mesqueeb** [TrustWallet/trust-wallet-ios#839]
From our findings most QR code scanners of ETH wallets use `eth` instead of `wei` for scanning the value amount.

`imToken`, `BRD wallet`, `Lykke` all use ETH instead of wei.

We'd love our payment app to work with as many wallets as possible. Do you think there's any chance you'll change `eth` to `wei` in the future?

PS: The closest thing we have to a standard is [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) also stating the value should be in `eth` not `wei`.

**Comment by vikmeup** [comment]
@mesqueeb that's a good idea, I will change this to decimal `value`. 

That's a plan to support 681 at some point, it's not being used much, but it's gonna be adapted soon!

**Comment by mesqueeb** [comment]
@vikmeup Thank you for the kind support.

In this [other issue](https://github.com/TrustWallet/trust-wallet-ios/issues/840) I opened I mentioned more about field names.

With this issue I wanted to point out the `eth` vs `wei` debate. : P 
Did you understand what I meant with that?

**Comment by vikmeup** [comment]
@mesqueeb I think we just need to adapt to whichever standard has more adaption.

**Comment by mesqueeb** [comment]
@vikmeup Exactly, as far as I know EIP-681 says the amount should be in `eth` and all wallets we tested use `eth`. Trust wallet is the only one we know of that uses `wei` instead.

**Comment by vikmeup** [comment]
@mesqueeb just added a quick fix to use whichever amount is the parameter: https://github.com/TrustWallet/trust-wallet-ios/commit/a3b7d9305ca6ce812529f118047d645873a8f78f

681 will be next, whenever we find time to implement.

**Comment by vikmeup** [comment]
@mesqueeb I think initially our plan was to support Ethereum, that's why we picked Wei and then realized that we gonna support more chains and `amount` in decimal just makes more sense.
