### ISSUE TITLE
[QR code issue] average USD is not filled in after scan

### ISSUE THREAD

**Issue by mesqueeb** [TrustWallet/trust-wallet-ios#858]
When scanning a QR code, the average `usd` is stays `0` even though the QR code had filled in the eth amount.

After deleting or adding 1 character in the ETH field it does get triggered and the `usd` amount appears underneath.

**Comment by vikmeup** [comment]
@OlegGordiichuk can you take a look?

**Comment by OlegGordiichuk** [comment]
Yeah I will take a look.

**Comment by mesqueeb** [comment]
@OlegGordiichuk The amount is filled in but when pressing the 'next' button it says 0 ETH.
When I go back, add a 0 then press next the proper ETH amount is filled in.

**Comment by OlegGordiichuk** [comment]
@mesqueeb will take a look in 1 hour.

**Comment by OlegGordiichuk** [comment]
@mesqueeb fixed. Thx for sharing of the problem.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3758731/43995155-b28fb8f8-9db1-11e8-89fb-666d7bab519d.gif)

**Comment by mesqueeb** [comment]
@OlegGordiichuk On my iPhone the bug is back where on the second page it will stay 0. Maybe this is regressed in one of the updates?
