### ISSUE TITLE
Закладки

### ISSUE THREAD

**Issue by Mazafaka666** [TrustWallet/trust-wallet-ios#873]
Пропали все закладки в браузеры после обновления. 
Нужно вернуть. Было ну очень удобно

**Comment by vikmeup** [comment]
@Mazafaka666 А сможешь обратно добавь которые там были? Возможно кеш уже не восстановим

**Comment by Mazafaka666** [comment]
Понял! Огромное спасибо! Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail01.08.2018, 22:25, "Viktor Radchenko" <notifications@github.com>:@Mazafaka666 Добавлю обратно сейчас!
Убираем их что бы новую версию в App Store закинуть, а то Apple иногда отвергает нас.
