### ISSUE TITLE
DApp browser stalls on cryptokitty page

### ISSUE THREAD

**Issue by James-Sangalli** [TrustWallet/trust-wallet-ios#903]
And maybe other dapp pages.

**Comment by mandelmonkey** [comment]
yes I noticed this too, but on our wallet that uses trust provider

**Comment by vikmeup** [comment]
Something has changed on CK side, but we are also working to improve our web3 provider. Hopefully to refactor within a week or two.

@hewigovens can give more updates on this

**Comment by mandelmonkey** [comment]
if you guys find a quick fix patch let us know, like wise if I do I will post here
hopefully CK can address there end

**Comment by choiceyou** [comment]
Report an error：

Undefined symbols for architecture arm64:
  "_random32", referenced from:
      _generate_k_random in ecdsa.o
      _random_buffer in rand.o
      _random_uniform in rand.o
      _random_permute in rand.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by James-Sangalli** [comment]
Downgrading web3js to 0.20.3 will fix this issue

**Comment by hewigovens** [comment]
We're refactoring and testing trust web3 provider, should fix this issue soon

**Comment by mandelmonkey** [comment]
@hewigovens any update on this?

**Comment by hewigovens** [comment]
we will release a new version with new provider to App Store soon

**Comment by vikmeup** [comment]
Closing this for now! New provider will be released next week

**Comment by mandelmonkey** [comment]
@vikmeup cool, is the new provider available https://github.com/TrustWallet/trust-web3-provider here?
