### ISSUE TITLE
Value of type 'Coin' has no member 'rawValue'      这个报错，请问如何解决！？

### ISSUE THREAD

**Issue by LBJCR7** [TrustWallet/trust-wallet-ios#906]
![0bd61942-eee8-46e8-9ceb-5f49844db9f7](https://user-images.githubusercontent.com/19280175/44461112-36aa8f80-a642-11e8-8856-cd4131e57a55.png)

**Comment by vikmeup** [comment]
Should not be an issue if you are using the `master` branch, Travis CI is green
