### ISSUE TITLE
Can I use a testnet from the iOS app?

### ISSUE THREAD

**Issue by evansjohnson** [TrustWallet/trust-wallet-ios#908]
[This issue](https://github.com/TrustWallet/trust-wallet-ios/issues/438) implies that at some point you could easily switch to a testnet.  I have gone through all of the in-app settings and could not find anything.

**Comment by AdMeen89** [comment]
Hey @evansjohnson. 

Unfortunately, it seems this option has been removed from application. If you look at the RPCServer.swift file and its early commits (eg 313c26c), you'll see that kovan, ropsten and other testnets have been contained which later have been removed.

**Comment by AdMeen89** [comment]
I've attached a example of supporting ropsten testnet. We can use it or create own implementation.
[ropsten-diff.txt](https://github.com/TrustWallet/trust-wallet-ios/files/2321618/ropsten-diff.txt)

**Comment by vikmeup** [comment]
I would recommend testing dapp development on MetaMask. We might be adding test networks back later, for now focus on delivering simpler interface for the users.

**Comment by evansjohnson** [comment]
I understand and appreciate the desire for delivering a simple interface!  Although the "Developer" submenu in settings seems like an unobtrusive place for this setting to live 🙂

I mainly wanted to test support for EIP712 typed data message signing which I now see there is an open issue for here #825 

I will keep an eye on that issue and lookout for testnet support so I can ensure our dApp will be compatable with Trust Wallet when we launch on mainnet!

**Comment by destinatis** [comment]
Lame.

**Comment by vikmeup** [comment]
@evansjohnson 721 is implemented on the iOS side, should be available within a couple of days on App Store.
@hewigovens

**Comment by theone3nu** [comment]
> I've attached a example of supporting ropsten testnet. You can use it or create own implementation. It isn't a beautiful code but it works.
> [ropsten-diff.txt](https://github.com/TrustWallet/trust-wallet-ios/files/2321618/ropsten-diff.txt)

How to use this file. What to do inorder to get test net accounts in trust wallet in ios simulator
