### ISSUE TITLE
Can support infura.io's V3 mode?

### ISSUE THREAD

**Issue by sa124a** [TrustWallet/trust-wallet-ios#918]

**Comment by vikmeup** [comment]
What's v3 mode?

**Comment by hewigovens** [comment]
What's the difference?

**Comment by sa124a** [comment]
If I use  https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxxx, the request will fail.
If I use  https://mainnet.infura.io/xxxxxxxxxxxxxxxxxxx, the request will succeed.

**Comment by hewigovens** [comment]
Can't find v3 here: https://infura.io/docs/api/get/symbolFull

**Comment by sa124a** [comment]
![image](https://user-images.githubusercontent.com/16516131/45672426-ae44df00-bb5a-11e8-8dfc-cc8bc8e3e160.png)


ye，文档还没更新对v3的说明，但有说明未来要以v3为主
Ye, the document has not updated the description of V3, but there are indications that V3 will be the main factor in the future.

**Comment by hewigovens** [comment]
Thanks for your information, we'll migrate it later

**Comment by sa124a** [comment]
You're welcome. I also have trouble about the V3 mode because there is no official document.

**Comment by hewigovens** [comment]
we don't use infura anymore
