### ISSUE TITLE
Use of undeclared type 'Coin'

### ISSUE THREAD

**Issue by cocoZ** [TrustWallet/trust-wallet-ios#921]
![image](https://user-images.githubusercontent.com/9474874/45461951-46e0f680-b738-11e8-96f1-d63530f49b29.png)

**Comment by cocoZ** [comment]
@

**Comment by Water-bamboo** [comment]
@cocoZ 我也遇到这个问题，请教下怎么解决的？

**Comment by JaneEyre2** [comment]
@cocoZ @Water-bamboo 我刚下载的项目也报了这个错，请问怎么解决的？

**Comment by tixguru-jemmy** [comment]
@cocoZ @Water-bamboo @JaneEyre2 請問有解決嗎？

**Comment by Water-bamboo** [comment]
有

发自我的 iPhone

**Comment by SuperDarrenChain** [comment]
有什么解决办法吗，我看了TrustCore (0.0.7)这个是他们的我们的是0.2.2，这个没有这个类怎么解决啊
