### ISSUE TITLE
About TrustWeb3Provider instantiation

### ISSUE THREAD

**Issue by zhuofanxu** [TrustWallet/trust-wallet-ios#929]
I find over the project and can't find the part of TrustWeb3Provider instantiation for web3 instance . could you explain it ?  thanks!

**Comment by stevemulligan** [comment]
If you are looking for where it sets the network to use, it's in Trust/Transactions/Storage/Session.swift line 32

And the web3 provider is set in JS inside Trust/Browser/Factory/WKWebViewConfiguration.swift line 23

Hope that helps.

**Comment by zhuofanxu** [comment]
thanks for reply!  but i'm looking for is that  `var web3Provider = new Trust(config); var web3 = new Web3(web3Provider)` like in chrome extension 'metamaks'

**Comment by hewigovens** [comment]
check: https://github.com/TrustWallet/trust-web3-provider/blob/master/Example/TrustWeb3Provider/WKUserScriptConfig.swift
