### ISSUE TITLE
QR Code Scanner for DApp Browser

### ISSUE THREAD

**Issue by ZitRos** [TrustWallet/trust-wallet-ios#934]
Hello! Thank you for an excellent wallet.

It would be much appreciated if you add a QR code to an embedded dApp browser. Let me know what do you think, thanks!

![image](https://user-images.githubusercontent.com/4989256/47863676-7b039a00-de00-11e8-9ffc-2207dbe1536c.png)

**Comment by vikmeup** [comment]
@ZitRos use deep links: https://medium.com/@trustwallet/mobile-dapps-with-deep-linking-and-trust-wallet-6a4712b9b9a4

to forward your users to dapp browser!

**Comment by ZitRos** [comment]
@vikmeup, deep links are not the complete solution. DApps doesn't always mean mobile apps!

**Read this:**

There is a desktop website where you are prompted to do some Ethereum action (donation, payment, whatever) with "Pay with web3/Metamask". (It's very common for people to have a mobile wallet and also a laptop for surfing, isn't it?). Now, you want to donate/pay/whatever using your mobile wallet. Would you manually type website's URL to your DApp browser, being an inexperienced user? Never! 95% of people doesn't even know what's "DApp browser" on mobile (only we, developers, know that it injects web3 provider thanks to this cool Trust feature). The only thing that works is to state on a desktop website clearly "scan this QR on your mobile wallet". By having `http(s)://` link mobile wallet can quickly recognize which action to perform (obviously, open link in DApp browser).

Yes, I am aware of QR code [EIP for Ethereum actions](https://github.com/ethereum/EIPs/issues/67), but if you have a fully-featured web app + dApp you may need a quick switch from desktop to a mobile.

Please respond :) Thanks!
