### ISSUE TITLE
ether  stolen 

### ISSUE THREAD

**Issue by Kim-Taehwan** [TrustWallet/trust-wallet-ios#952]
I was also stolen ether.
On iphone, use https://www.myetherwallet.com and trust wallet.

**Comment by tixguru-jemmy** [comment]
Hi Kim-Taehwan, I think you need to submit more information on this kind of matter.
I don't know about myetherwallet.com but you might need to provide more 'evidence' for TrustWallet as to what happened leading to the said 'stolen' incident.

--Jemmy
