### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by itsmylife44** [TrustWallet/trust-wallet-ios#954]
Hello , i am use xcode 10.2 

trying to build 
`Build input file cannot be found: '/Users/trust-wallet-ios/Trust/R.generated.swift'`

![immagine](https://user-images.githubusercontent.com/34112129/52434455-a2f54e80-2b0f-11e9-9378-c2303a329185.png)

**Comment by tixguru-jemmy** [comment]
Hi there, I tried the instruction from the following and it seems to work:
https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md
There's a part on "Upgrading to 5.0".
Give it a try.

--Jemmy

**Comment by itsmylife44** [comment]
It works . 

Thank you too much ))

**Comment by ivrusuboca** [comment]
Hi . Please close this issue , since your confirmed it worked :) . Thanks.
