### ISSUE TITLE
Use of undeclared type 'Coin'

### ISSUE THREAD

**Issue by tixguru-jemmy** [TrustWallet/trust-wallet-ios#955]
Xcode Version 10.1 (10B61)
R.swift 5.0.2
R.swift.Library 5.0.0
TrezorCrypto 0.0.9
TrustCore 0.2.2
TrustKeystore 0.5.1
TrustWalletSDK 0.0.1
TrustWeb3Provider 0.1.7

Build Trust: Failed with Swift Compile Error Message: "Use of undeclared type 'Coin'"
I have seen case#921 and case#948 but they do not say how it was resolved.

--Jemmy

**Comment by zhaoychehe** [comment]
Clone this repository.
Run 'make bootstrap' to install tools and dependencies.

**Comment by hewigovens** [comment]
Try `CoinType` or `AppCoin`
