### ISSUE TITLE
Incoming transactions marked as Sent causing negative amount on Non Multi-Coin wallets

### ISSUE THREAD

**Issue by mlvein** [TrustWallet/trust-wallet-ios#958]
![IMG_5289](https://user-images.githubusercontent.com/6550846/55279703-4fa4bd00-5356-11e9-9340-8bc6620c56b7.PNG)

Sent ether to my old wallet (not multi-coin) and all transactions are marked as sent even the received ones. [https://etherscan.io/address/0x3778eb15c353f56e7634b16ca3cc07b82648f879](etherscan) shows true amount but Trust Wallet doesn't display it and I can't transfer it out since it shows 'insufficient balance'

This issue doesn't seem to affect Multi-coin wallets only the non multi-coin ones. Hope this gets fixed!

**Comment by mlvein** [comment]
Fixed it by deleting and reimporting wallet as advised. Thanks!

**Comment by vikmeup** [comment]
Can you try to install latest version and see if it fixed old wallet? We just pushed new version out

**Comment by mlvein** [comment]
I actually encountered the problem after updating to the recent version. It didn’t seem to affect my multi-coin wallets though

**Comment by vikmeup** [comment]
Can you try latest version? It went out(10AM PST) today - it should fix this issue.

**Comment by mlvein** [comment]
It’s all fixed now. Thank you!!
